export const THEMES = [
  {
    id: "dark", label: "ダーク", preview: "bg-gray-700",
    bg: "bg-gray-900", card: "bg-slate-700", border: "border-slate-500", innerCard: "bg-slate-600",
    titleText: "text-white", bodyText: "text-gray-100", subText: "text-gray-300",
    accent: "text-indigo-300", bar: "bg-indigo-400",
    staminaFill: "bg-yellow-400", staminaBorder: "border-yellow-300",
    reviewFill: "bg-blue-400", reviewBorder: "border-blue-300",
    divider: "border-slate-500",
    nav: "bg-slate-800", navBorder: "border-slate-600", navActive: "text-indigo-300", navInactive: "text-gray-400",
    avatarBg: "bg-indigo-500", avatarText: "text-white",
    startBtn: "bg-indigo-500 hover:bg-indigo-400", startText: "text-white",
    reviewBtn: "bg-slate-600 hover:bg-slate-500", reviewText: "text-gray-100",
    ticketNum: "text-yellow-300", allClearText: "text-yellow-300",
    bannerBg: "bg-gradient-to-r from-indigo-700 to-slate-600",
  },
  {
    id: "pink", label: "ピンク", preview: "bg-rose-400",
    bg: "bg-rose-50", card: "bg-white", border: "border-rose-300", innerCard: "bg-rose-100",
    titleText: "text-rose-900", bodyText: "text-rose-800", subText: "text-rose-500",
    accent: "text-rose-700", bar: "bg-rose-500",
    staminaFill: "bg-rose-500", staminaBorder: "border-rose-400",
    reviewFill: "bg-pink-500", reviewBorder: "border-pink-400",
    divider: "border-rose-200",
    nav: "bg-white", navBorder: "border-rose-200", navActive: "text-rose-700", navInactive: "text-rose-400",
    avatarBg: "bg-rose-600", avatarText: "text-white",
    startBtn: "bg-rose-600 hover:bg-rose-500", startText: "text-white",
    reviewBtn: "bg-rose-200 hover:bg-rose-300", reviewText: "text-rose-900",
    ticketNum: "text-rose-700", allClearText: "text-rose-700",
    bannerBg: "bg-gradient-to-r from-rose-400 to-pink-400",
  },
  {
    id: "mint", label: "ミント", preview: "bg-teal-400",
    bg: "bg-teal-50", card: "bg-white", border: "border-teal-300", innerCard: "bg-teal-100",
    titleText: "text-teal-900", bodyText: "text-teal-900", subText: "text-teal-600",
    accent: "text-teal-700", bar: "bg-teal-500",
    staminaFill: "bg-teal-500", staminaBorder: "border-teal-400",
    reviewFill: "bg-cyan-500", reviewBorder: "border-cyan-400",
    divider: "border-teal-200",
    nav: "bg-white", navBorder: "border-teal-200", navActive: "text-teal-700", navInactive: "text-teal-400",
    avatarBg: "bg-teal-600", avatarText: "text-white",
    startBtn: "bg-teal-600 hover:bg-teal-500", startText: "text-white",
    reviewBtn: "bg-teal-200 hover:bg-teal-300", reviewText: "text-teal-900",
    ticketNum: "text-teal-700", allClearText: "text-teal-700",
    bannerBg: "bg-gradient-to-r from-teal-400 to-cyan-400",
  },
  {
    id: "cream", label: "クリーム", preview: "bg-amber-400",
    bg: "bg-amber-50", card: "bg-white", border: "border-amber-300", innerCard: "bg-amber-100",
    titleText: "text-amber-900", bodyText: "text-amber-900", subText: "text-amber-600",
    accent: "text-amber-700", bar: "bg-amber-500",
    staminaFill: "bg-amber-500", staminaBorder: "border-amber-400",
    reviewFill: "bg-yellow-500", reviewBorder: "border-yellow-400",
    divider: "border-amber-200",
    nav: "bg-white", navBorder: "border-amber-200", navActive: "text-amber-700", navInactive: "text-amber-400",
    avatarBg: "bg-amber-600", avatarText: "text-white",
    startBtn: "bg-amber-600 hover:bg-amber-500", startText: "text-white",
    reviewBtn: "bg-amber-200 hover:bg-amber-300", reviewText: "text-amber-900",
    ticketNum: "text-amber-700", allClearText: "text-amber-700",
    bannerBg: "bg-gradient-to-r from-amber-400 to-yellow-400",
  },
  {
    id: "mono", label: "茶色", preview: "bg-stone-600",
    bg: "bg-stone-50", card: "bg-white", border: "border-stone-400", innerCard: "bg-stone-100",
    titleText: "text-stone-900", bodyText: "text-stone-900", subText: "text-stone-600",
    accent: "text-amber-800", bar: "bg-amber-700",
    staminaFill: "bg-amber-700", staminaBorder: "border-amber-600",
    reviewFill: "bg-stone-500", reviewBorder: "border-stone-400",
    divider: "border-stone-300",
    nav: "bg-white", navBorder: "border-stone-300", navActive: "text-amber-800", navInactive: "text-stone-400",
    avatarBg: "bg-amber-800", avatarText: "text-white",
    startBtn: "bg-amber-800 hover:bg-amber-700", startText: "text-white",
    reviewBtn: "bg-stone-200 hover:bg-stone-300", reviewText: "text-stone-900",
    ticketNum: "text-amber-800", allClearText: "text-amber-800",
    bannerBg: "bg-gradient-to-r from-amber-800 to-stone-600",
  },
];

export type Theme = (typeof THEMES)[number];
