-- ベビーレベル単語データ（CSVから変換・重複除去済み）
-- 実行前に schema_words_update.sql を先に実行してください

INSERT INTO words (level, word, meaning, part_of_speech, reading, example_en, example_ja)
VALUES
  ('baby', 'cat',      'ねこ',              'noun', 'キャット',    'I see a cat.',                   'ねこが見えるよ。'),
  ('baby', 'dog',      'いぬ',              'noun', 'ドッグ',      'The dog is big.',                'その犬は大きいよ。'),
  ('baby', 'red',      'あかい',            'adj',  'レッド',      'I like red.',                    'あかが好き。'),
  ('baby', 'blue',     'あおい',            'adj',  'ブルー',      'The ball is blue.',              'そのボールはあおいよ。'),
  ('baby', 'run',      'はしる',            'verb', 'ラン',        'I can run fast.',                'はやくはしれるよ。'),
  ('baby', 'jump',     'ジャンプする',       'verb', 'ジャンプ',    'Jump high!',                     'たかくジャンプして！'),
  ('baby', 'apple',    'りんご',            'noun', 'アップル',    'I eat an apple.',                'りんごをたべるよ。'),
  ('baby', 'ball',     'ボール',            'noun', 'ボール',      'Throw the ball!',                'ボールをなげて！'),
  ('baby', 'hand',     'て',               'noun', 'ハンド',      'Wash your hands.',               'てをあらってね。'),
  ('baby', 'foot',     'あし',             'noun', 'フット',      'My foot hurts.',                 'あしがいたいよ。'),
  ('baby', 'sun',      'たいよう',          'noun', 'サン',        'The sun is hot.',                'たいようはあついよ。'),
  ('baby', 'milk',     'ぎゅうにゅう',       'noun', 'ミルク',      'I drink milk.',                  'ぎゅうにゅうをのむよ。'),
  ('baby', 'big',      'おおきい',          'adj',  'ビッグ',      'That is a big car.',             'あれはおおきいくるまだね。'),
  ('baby', 'mom',      'ママ',             'noun', 'マム',        'I love my mom.',                 'ママがだいすき。'),
  ('baby', 'dad',      'パパ',             'noun', 'ダッド',      'Dad reads to me.',               'パパがよんでくれるよ。'),
  ('baby', 'bed',      'ベッド',            'noun', 'ベッド',      'Go to bed now.',                 'もうねなさい。'),
  ('baby', 'hat',      'ぼうし',            'noun', 'ハット',      'I have a hat.',                  'ぼうしをもっているよ。'),
  ('baby', 'one',      'いち',             'noun', 'ワン',        'I am one year old.',             'いっさいだよ。'),
  ('baby', 'two',      'に',              'noun', 'トゥー',      'I see two birds.',               'にわのとりがみえるよ。'),
  ('baby', 'book',     'ほん',             'noun', 'ブック',      'Read me a book.',                'ほんをよんで。'),
  ('baby', 'pig',      'ブタ',             'noun', 'ピッグ',      'The pig is pink.',               'そのブタはピンクいろです。'),
  ('baby', 'car',      'くるま',            'noun', 'カー',        'I see a red car.',               'あかいくるまがみえます。'),
  ('baby', 'egg',      'たまご',            'noun', 'エッグ',      'I eat an egg.',                  'たまごをたべます。'),
  ('baby', 'cup',      'コップ',            'noun', 'カップ',      'My cup is full.',                'わたしのコップはいっぱいです。'),
  ('baby', 'nose',     'はな',             'noun', 'ノウズ',      'Touch your nose.',               'あなたのはなをさわってください。'),
  ('baby', 'ear',      'みみ',             'noun', 'イヤー',      'I have two ears.',               'みみがふたつあります。'),
  ('baby', 'leg',      'あし',             'noun', 'レッグ',      'My leg hurts.',                  'あしがいたいです。'),
  ('baby', 'sit',      'すわる',            'verb', 'シット',      'Please sit down.',               'すわってください。'),
  ('baby', 'hot',      'あつい',            'adj',  'ホット',      'The soup is hot.',               'そのスープはあついです。'),
  ('baby', 'tree',     'き',              'noun', 'トゥリー',    'The tree is tall.',              'そのきはたかいです。'),
  ('baby', 'fish',     'さかな',            'noun', 'フィッシュ',  'The fish is swimming.',          'さかながおよいでいます。'),
  ('baby', 'bee',      'ハチ',             'noun', 'ビー',        'The bee is on the flower.',      'ハチがはなのうえにいます。'),
  ('baby', 'bag',      'かばん',            'noun', 'バッグ',      'My bag is heavy.',               'わたしのかばんはおもいです。'),
  ('baby', 'pen',      'ペン',             'noun', 'ペン',        'I have a blue pen.',             'あおいペンをもっています。'),
  ('baby', 'box',      'はこ',             'noun', 'ボックス',    'The box is empty.',              'そのはこはからです。'),
  ('baby', 'three',    'さん',             'noun', 'スリー',      'I have three cookies.',          'クッキーをみっつもっています。'),
  ('baby', 'yellow',   'きいろ',            'adj',  'イエロー',    'The banana is yellow.',          'そのバナナはきいろです。'),
  ('baby', 'green',    'みどり',            'adj',  'グリーン',    'The frog is green.',             'そのカエルはみどりいろです。'),
  ('baby', 'cake',     'ケーキ',            'noun', 'ケイク',      'I like chocolate cake.',         'チョコレートケーキがすきです。'),
  ('baby', 'rain',     'あめ',             'noun', 'レイン',      'I see the rain.',                'あめがみえます。'),
  ('baby', 'net',      'あみ',             'noun', 'ネット',      'The fish is in the net.',        'さかながあみのなかにいます。'),
  ('baby', 'hen',      'めんどり',          'noun', 'ヘン',        'The hen lays eggs.',             'めんどりがたまごをうむよ。'),
  ('baby', 'arm',      'うで',             'noun', 'アーム',      'I raise my arm.',                'うでをあげるよ。'),
  ('baby', 'toe',      'つまさき',          'noun', 'トウ',        'I can wiggle my toes.',          'あしのゆびをうごかせるよ。'),
  ('baby', 'eye',      'め',              'noun', 'アイ',        'I have two eyes.',               'めがふたつあるよ。'),
  ('baby', 'four',     'し',              'noun', 'フォー',      'I have four apples.',            'りんごをよっつもっているよ。'),
  ('baby', 'five',     'ご',              'noun', 'ファイブ',    'I see five birds.',              'とりをごわみるよ。'),
  ('baby', 'bus',      'バス',             'noun', 'バス',        'I ride the bus to school.',      'バスでがっこうにいくよ。'),
  ('baby', 'ice',      'こおり',            'noun', 'アイス',      'The ice is cold.',               'こおりはつめたいよ。'),
  ('baby', 'rice',     'ごはん',            'noun', 'ライス',      'I eat rice every day.',          'まいにちごはんをたべるよ。'),
  ('baby', 'moon',     'つき',             'noun', 'ムーン',      'I see the moon at night.',       'よるにつきをみるよ。'),
  ('baby', 'star',     'ほし',             'noun', 'スター',      'I see many stars tonight.',      'こんやたくさんのほしがみえるよ。'),
  ('baby', 'duck',     'アヒル',            'noun', 'ダック',      'The duck swims in the pond.',    'アヒルがいけでおよいでいるよ。'),
  ('baby', 'frog',     'カエル',            'noun', 'フロッグ',    'The frog jumps high.',           'カエルがたかくとぶよ。'),
  ('baby', 'meat',     'にく',             'noun', 'ミート',      'I like to eat meat.',            'にくをたべるのがすきだよ。'),
  ('baby', 'snow',     'ゆき',             'noun', 'スノウ',      'I play in the snow.',            'ゆきのなかであそぶよ。'),
  ('baby', 'cold',     'つめたい',          'adj',  'コールド',    'The water is cold.',             'みずがつめたいよ。'),
  ('baby', 'gate',     'もん',             'noun', 'ゲート',      'I open the gate.',               'もんをあけるよ。'),
  ('baby', 'fan',      'せんぷうき',         'noun', 'ファン',      'The fan is on.',                 'せんぷうきがついているよ。'),
  ('baby', 'six',      'ろく',             'noun', 'シックス',    'I have six toys.',               'おもちゃをむっつもっています。'),
  ('baby', 'seven',    'なな',             'noun', 'セブン',      'There are seven days in a week.','いっしゅうかんはなのかです。'),
  ('baby', 'cow',      'うし',             'noun', 'カウ',        'The cow is in the field.',       'うしはのはらにいます。'),
  ('baby', 'horse',    'うま',             'noun', 'ホース',      'I like to ride a horse.',        'うまにのるのがすきです。'),
  ('baby', 'bird',     'とり',             'noun', 'バード',      'The bird is singing.',           'とりがうたっています。'),
  ('baby', 'door',     'ドア',             'noun', 'ドア',        'Open the door, please.',         'ドアをあけてください。'),
  ('baby', 'boat',     'ボート',            'noun', 'ボート',      'We go in a boat.',               'ボートにのります。'),
  ('baby', 'coat',     'コート',            'noun', 'コート',      'Put on your coat.',              'コートをきなさい。'),
  ('baby', 'goat',     'ヤギ',             'noun', 'ゴート',      'The goat eats grass.',           'ヤギはくさをたべます。'),
  ('baby', 'soap',     'せっけん',          'noun', 'ソープ',      'Wash your hands with soap.',     'せっけんでてをあらいなさい。'),
  ('baby', 'teeth',    'は（複数）',         'noun', 'ティース',    'Brush your teeth every day.',    'まいにちはをみがきなさい。'),
  ('baby', 'bear',     'クマ',             'noun', 'ベア',        'The bear is sleeping.',          'クマはねむっています。'),
  ('baby', 'corn',     'とうもろこし',       'noun', 'コーン',      'I like to eat corn.',            'とうもろこしをたべるのがすきです。'),
  ('baby', 'fork',     'フォーク',          'noun', 'フォーク',    'Use a fork to eat.',             'フォークをつかってたべなさい。'),
  ('baby', 'pear',     'なし',             'noun', 'ペア',        'This pear is sweet.',            'このなしはあまいです。'),
  ('baby', 'bread',    'パン',             'noun', 'ブレッド',    'I eat bread for breakfast.',     'あさごはんにパンをたべます。'),
  ('baby', 'hair',     'かみ',             'noun', 'ヘア',        'She has long hair.',             'かのじょはながいかみをしています。'),
  ('baby', 'chair',    'いす',             'noun', 'チェア',      'Sit on the chair.',              'いすにすわりなさい。'),
  ('baby', 'pink',     'ピンクいろ',         'adj',  'ピンク',      'I like pink flowers.',           'ピンクのはながすきです。'),
  ('baby', 'walk',     'あるく',            'verb', 'ウォーク',    'I walk to school.',              'がっこうまであるきます。'),
  ('baby', 'head',     'あたま',            'noun', 'ヘッド',      'Put the hat on your head.',      'ぼうしをあたまにかぶりなさい。'),
  ('baby', 'eat',      'たべる',            'verb', 'イート',      'I eat breakfast every day.',     'まいにちあさごはんをたべます。'),
  ('baby', 'orange',   'オレンジ',          'noun', 'オレンジ',    'This orange is sweet.',          'このオレンジはあまいです。'),
  ('baby', 'water',    'みず',             'noun', 'ウォーター',  'Drink some water.',              'みずをのみなさい。'),
  ('baby', 'sheep',    'ひつじ',            'noun', 'シープ',      'The sheep is white.',            'そのひつじはしろいです。'),
  ('baby', 'eight',    'はち',             'noun', 'エイト',      'I have eight crayons.',          'クレヨンをはっぽんもっています。'),
  ('baby', 'nine',     'きゅう',            'noun', 'ナイン',      'There are nine balls.',          'ボールがきゅうこあります。'),
  ('baby', 'ten',      'じゅう',            'noun', 'テン',        'I can count to ten.',            'じゅうまでかぞえられます。'),
  ('baby', 'mouth',    'くち',             'noun', 'マウス',      'Open your mouth wide.',          'くちをおおきくあけなさい。'),
  ('baby', 'see',      'みる',             'verb', 'シー',        'I see a bird in the tree.',      'きのなかにとりがみえます。'),
  ('baby', 'look',     'みる',             'verb', 'ルック',      'Look at the sky.',               'そらをみなさい。'),
  ('baby', 'black',    'くろ',             'adj',  'ブラック',    'The cat is black.',              'そのねこはくろいです。'),
  ('baby', 'white',    'しろ',             'adj',  'ホワイト',    'I like white clouds.',           'しろいくもがすきです。'),
  ('baby', 'sock',     'くつした',          'noun', 'ソック',      'Put on your socks.',             'くつしたをはきなさい。'),
  ('baby', 'shoe',     'くつ',             'noun', 'シュー',      'My shoes are new.',              'わたしのくつはあたらしいです。'),
  ('baby', 'play',     'あそぶ',            'verb', 'プレイ',      'Let''s play together.',          'いっしょにあそびましょう。'),
  ('baby', 'toy',      'おもちゃ',          'noun', 'トイ',        'This is my favorite toy.',       'これはおきにいりのおもちゃです。'),
  ('baby', 'baby',     'あかちゃん',         'noun', 'ベイビー',    'The baby is sleeping.',          'あかちゃんはねむっています。'),
  ('baby', 'happy',    'うれしい',          'adj',  'ハッピー',    'I am happy today.',              'きょうはうれしいです。'),
  ('baby', 'sand',     'すな',             'noun', 'サンド',      'I like to play in the sand.',    'すなであそぶのがすきです。'),
  ('baby', 'ant',      'アリ',             'noun', 'アント',      'Look at the ant on the ground.', 'じめんのアリをみて。'),
  ('baby', 'fox',      'キツネ',            'noun', 'フォックス',  'The fox runs fast.',             'キツネははやくはしる。'),
  ('baby', 'jam',      'ジャム',            'noun', 'ジャム',      'I like jam on my bread.',        'パンにジャムをつけるのがすき。'),
  ('baby', 'king',     'おうさま',          'noun', 'キング',      'The king lives in a big castle.','おうさまはおおきなおしろにすんでいます。'),
  ('baby', 'lamp',     'ランプ',            'noun', 'ランプ',      'Turn on the lamp, please.',      'ランプをつけてください。'),
  ('baby', 'nest',     'す',              'noun', 'ネスト',      'The bird sits in the nest.',     'とりがすにすわっています。'),
  ('baby', 'tail',     'しっぽ',            'noun', 'テイル',      'The dog wags its tail.',         'いぬがしっぽをふっています。'),
  ('baby', 'wing',     'つばさ',            'noun', 'ウィング',    'The bird has two wings.',        'とりにはふたつのつばさがあります。'),
  ('baby', 'zoo',      'どうぶつえん',       'noun', 'ズー',        'We go to the zoo on Sunday.',    'にちようびにどうぶつえんにいきます。'),
  ('baby', 'bell',     'ベル',             'noun', 'ベル',        'Ring the bell, please.',         'ベルをならしてください。'),
  ('baby', 'pool',     'プール',            'noun', 'プール',      'The children play in the pool.', 'こどもたちはプールであそびます。'),
  ('baby', 'bone',     'ほね',             'noun', 'ボーン',      'The dog has a big bone.',        'いぬはおおきなほねをもっています。'),
  ('baby', 'gift',     'プレゼント',         'noun', 'ギフト',      'I have a gift for you.',         'あなたにプレゼントがあります。'),
  ('baby', 'hill',     'おか',             'noun', 'ヒル',        'We walk up the hill.',           'おかをのぼります。'),
  ('baby', 'neck',     'くび',             'noun', 'ネック',      'My neck hurts.',                 'くびがいたいです。'),
  ('baby', 'road',     'みち',             'noun', 'ロード',      'The road is wide.',              'そのみちはひろいです。'),
  ('baby', 'drum',     'ドラム',            'noun', 'ドラム',      'I play the drum.',               'ドラムをえんそうします。'),
  ('baby', 'flag',     'はた',             'noun', 'フラッグ',    'The flag is red and white.',     'そのはたはあかとしろです。'),
  ('baby', 'chest',    'むね',             'noun', 'チェスト',    'My chest is strong.',            'むねがつよいです。'),
  ('baby', 'desk',     'つくえ',            'noun', 'デスク',      'The desk is brown.',             'そのつくえはちゃいろです。'),
  ('baby', 'grass',    'くさ',             'noun', 'グラス',      'The grass is wet.',              'くさはぬれています。'),
  ('baby', 'cheek',    'ほお',             'noun', 'チーク',      'Her cheeks are pink.',           'かのじょのほおはピンクいろです。'),
  ('baby', 'stone',    'いし',             'noun', 'ストーン',    'I found a big stone.',           'おおきないしをみつけました。'),
  ('baby', 'grape',    'ぶどう',            'noun', 'グレープ',    'I eat grapes every day.',        'まいにちぶどうをたべます。'),
  ('baby', 'tiger',    'トラ',             'noun', 'タイガー',    'The tiger is big.',              'そのトラはおおきいです。'),
  ('baby', 'cloud',    'くも',             'noun', 'クラウド',    'I see a white cloud.',           'しろいくもをみます。'),
  ('baby', 'leaf',     'は',              'noun', 'リーフ',      'The leaf is green.',             'そのははみどりいろです。'),
  ('baby', 'wind',     'かぜ',             'noun', 'ウィンド',    'The wind is strong.',            'かぜがつよいです。'),
  ('baby', 'chin',     'あご',             'noun', 'チン',        'He has a small chin.',           'かれはちいさなあごをもっています。'),
  ('baby', 'peach',    'もも',             'noun', 'ピーチ',      'This peach is sweet.',           'このももはあまいです。'),
  ('baby', 'banana',   'バナナ',            'noun', 'バナナ',      'I like to eat a banana.',        'バナナをたべるのがすきです。'),
  ('baby', 'cookie',   'クッキー',          'noun', 'クッキー',    'Mom made cookies today.',        'おかあさんがクッキーをつくりました。'),
  ('baby', 'spoon',    'スプーン',          'noun', 'スプーン',    'Use a spoon to eat your soup.',  'スープをたべるのにスプーンをつかいなさい。'),
  ('baby', 'knife',    'ナイフ',            'noun', 'ナイフ',      'Be careful with the knife.',     'ナイフにはきをつけなさい。'),
  ('baby', 'plate',    'おさら',            'noun', 'プレート',    'Put the food on your plate.',    'たべものをおさらにのせなさい。'),
  ('baby', 'bowl',     'ボウル',            'noun', 'ボウル',      'I eat cereal in a bowl.',        'ボウルでシリアルをたべます。'),
  ('baby', 'turtle',   'カメ',             'noun', 'タートル',    'The turtle walks very slowly.',  'カメはとてもゆっくりあるきます。'),
  ('baby', 'rabbit',   'ウサギ',            'noun', 'ラビット',    'The rabbit hops in the garden.', 'ウサギがにわでぴょんぴょんはねています。'),
  ('baby', 'mouse',    'ネズミ',            'noun', 'マウス',      'A little mouse ran across.',     'ちいさなネズミがよこぎりました。'),
  ('baby', 'snake',    'ヘビ',             'noun', 'スネーク',    'The snake slides on the ground.','ヘビがじめんをすべっています。'),
  ('baby', 'lion',     'ライオン',          'noun', 'ライオン',    'The lion has a loud roar.',      'ライオンはおおきなこえでなきます。'),
  ('baby', 'monkey',   'サル',             'noun', 'モンキー',    'The monkey swings from trees.',  'サルがきからきへゆれています。'),
  ('baby', 'elephant', 'ゾウ',             'noun', 'エレファント', 'The elephant has big ears.',     'ゾウはおおきなみみをもっています。'),
  ('baby', 'purple',   'むらさきいろ',       'adj',  'パープル',    'I have a purple balloon.',       'むらさきのふうせんをもっています。'),
  ('baby', 'brown',    'ちゃいろ',          'adj',  'ブラウン',    'The bear is brown.',             'そのクマはちゃいろです。'),
  ('baby', 'sleep',    'ねむる',            'verb', 'スリープ',    'I sleep in my bed at night.',    'よるベッドでねむります。'),
  ('baby', 'drink',    'のむ',             'verb', 'ドリンク',    'Drink your milk.',               'ミルクをのみなさい。'),
  ('baby', 'sing',     'うたう',            'verb', 'シング',      'The birds sing in the morning.', 'とりたちはあさにうたいます。'),
  ('baby', 'smile',    'わらう',            'verb', 'スマイル',    'Smile for the photo!',           'しゃしんのためにわらって！'),
  ('baby', 'feet',     'あし（複数）',       'noun', 'フィート',    'I have two feet.',               'ふたつのあしがあります。'),
  ('baby', 'face',     'かお',             'noun', 'フェイス',    'Wash your face.',                'かおをあらいなさい。'),
  ('baby', 'flower',   'はな',             'noun', 'フラワー',    'The flower is pink.',            'そのはなはピンクです。'),
  ('baby', 'house',    'いえ',             'noun', 'ハウス',      'This is my house.',              'これはわたしのいえです。'),
  ('baby', 'train',    'でんしゃ',          'noun', 'トレイン',    'I see a train.',                 'でんしゃをみます。'),
  ('baby', 'plane',    'ひこうき',          'noun', 'プレイン',    'The plane is in the sky.',       'ひこうきはそらにあります。'),
  ('baby', 'pants',    'ズボン',            'noun', 'パンツ',      'My pants are blue.',             'ズボンはあおいです。'),
  ('baby', 'shirt',    'シャツ',            'noun', 'シャート',    'I have a red shirt.',            'あかいシャツをもっています。'),
  ('baby', 'cheese',   'チーズ',            'noun', 'チーズ',      'I like cheese.',                 'チーズがすきです。'),
  ('baby', 'pizza',    'ピザ',             'noun', 'ピザ',        'We eat pizza for dinner.',       'ゆうしょくにピザをたべます。'),
  ('baby', 'come',     'くる',             'verb', 'カム',        'Come here!',                     'こっちにきて！'),
  ('baby', 'go',       'いく',             'verb', 'ゴー',        'Let''s go home.',                'いえにかえりましょう。'),
  ('baby', 'kick',     'ける',             'verb', 'キック',      'I kick the ball.',               'ボールをけります。'),
  ('baby', 'spin',     'まわる',            'verb', 'スピン',      'I spin in a circle.',            'まるくまわります。'),
  ('baby', 'clap',     'てをたたく',         'verb', 'クラップ',    'We clap our hands.',             'てをたたきます。'),
  ('baby', 'hug',      'だきしめる',         'verb', 'ハグ',        'I hug my mom.',                  'ママをだきしめます。'),
  ('baby', 'wave',     'てをふる',          'verb', 'ウェイブ',    'I wave to my friend.',           'ともだちにてをふります。'),
  ('baby', 'open',     'あける',            'verb', 'オープン',    'Please open the door.',          'ドアをあけてください。'),
  ('baby', 'bat',      'バット',            'noun', 'バット',      'He has a red bat.',              'あかいバットをもっています。'),
  ('baby', 'vest',     'ベスト',            'noun', 'ベスト',      'He wears a blue vest.',          'あおいベストをきています。'),
  ('baby', 'well',     'いど',             'noun', 'ウェル',      'We get water from the well.',    'いどからみずをくみます。')
ON CONFLICT (word, level) DO NOTHING;
