-- ============================================================
-- 中学生レベル問題 400問
-- source: junior_200_questions.csv + junior_grammar_200.csv
-- 既存の junior 問題を置き換える
-- ============================================================

DELETE FROM questions WHERE level = 'junior';

INSERT INTO questions (level, sentence, japanese, words, punctuation, hint) VALUES
('junior', 'They do my homework every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'do', 'my', 'homework', 'every', 'day'], '.', 'do'),
('junior', 'They buy some food every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'buy', 'some', 'food', 'every', 'day'], '.', 'buy'),
('junior', 'I clean my room tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'clean', 'my', 'room', 'tonight'], '.', 'clean'),
('junior', 'They call my mother now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'call', 'my', 'mother', 'now'], '.', 'call'),
('junior', 'I go to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'We watch TV today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'watch', 'TV', 'today'], '.', 'watch'),
('junior', 'They listen to music now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'listen', 'to', 'music', 'now'], '.', 'listen'),
('junior', 'She walk to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'walk', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'You study English after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'study', 'English', 'after', 'school'], '.', 'study'),
('junior', 'He use my phone tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'use', 'my', 'phone', 'tonight'], '.', 'use'),
('junior', 'They watch TV later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'watch', 'TV', 'later'], '.', 'watch'),
('junior', 'They buy some food now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'buy', 'some', 'food', 'now'], '.', 'buy'),
('junior', 'She take a bus later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'They meet my friend tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'meet', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'You use my phone every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'use', 'my', 'phone', 'every', 'day'], '.', 'use'),
('junior', 'You play soccer every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'play', 'soccer', 'every', 'day'], '.', 'play'),
('junior', 'She buy some food this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'buy', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'We take a bus now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'take', 'a', 'bus', 'now'], '.', 'take'),
('junior', 'We buy some food tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'You eat lunch now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'eat', 'lunch', 'now'], '.', 'eat'),
('junior', 'You go to school now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'go', 'to', 'school', 'now'], '.', 'go'),
('junior', 'He run in the park today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'run', 'in', 'the', 'park', 'today'], '.', 'run'),
('junior', 'He use my phone this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'use', 'my', 'phone', 'this', 'morning'], '.', 'use'),
('junior', 'I run in the park this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'run', 'in', 'the', 'park', 'this', 'morning'], '.', 'run'),
('junior', 'They run in the park tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'run', 'in', 'the', 'park', 'tonight'], '.', 'run'),
('junior', 'She call my mother tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'call', 'my', 'mother', 'tonight'], '.', 'call'),
('junior', 'You listen to music tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'listen', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'We use my phone this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'use', 'my', 'phone', 'this', 'morning'], '.', 'use'),
('junior', 'We walk to school this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'walk', 'to', 'school', 'this', 'morning'], '.', 'walk'),
('junior', 'They read a book every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'She go to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'You open the door every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'open', 'the', 'door', 'every', 'day'], '.', 'open'),
('junior', 'I open the door this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'open', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'They go to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'She walk to school every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'walk', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'I do my homework tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'I read a book after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'read', 'a', 'book', 'after', 'school'], '.', 'read'),
('junior', 'He read a book this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'read', 'a', 'book', 'this', 'morning'], '.', 'read'),
('junior', 'I drink water after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'drink', 'water', 'after', 'school'], '.', 'drink'),
('junior', 'He clean my room now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'now'], '.', 'clean'),
('junior', 'We walk to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'walk', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'You open the door tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'You help my friend every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'help', 'my', 'friend', 'every', 'day'], '.', 'help'),
('junior', 'You drink water today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'drink', 'water', 'today'], '.', 'drink'),
('junior', 'He clean my room now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'now'], '.', 'clean'),
('junior', 'She meet my friend every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'meet', 'my', 'friend', 'every', 'day'], '.', 'meet'),
('junior', 'You buy some food tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'She buy some food this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'buy', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'They listen to music every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'They play soccer today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'You drink water this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'drink', 'water', 'this', 'morning'], '.', 'drink'),
('junior', 'He buy some food later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'buy', 'some', 'food', 'later'], '.', 'buy'),
('junior', 'I take a bus later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'They go to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'He play soccer after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'play', 'soccer', 'after', 'school'], '.', 'play'),
('junior', 'You walk to school later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'He listen to music now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'listen', 'to', 'music', 'now'], '.', 'listen'),
('junior', 'She eat lunch now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'eat', 'lunch', 'now'], '.', 'eat'),
('junior', 'He clean my room after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'after', 'school'], '.', 'clean'),
('junior', 'You use my phone today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'use', 'my', 'phone', 'today'], '.', 'use'),
('junior', 'You listen to music every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I go to school this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'go', 'to', 'school', 'this', 'morning'], '.', 'go'),
('junior', 'He clean my room this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'this', 'morning'], '.', 'clean'),
('junior', 'He go to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'They go to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'They meet my friend now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'meet', 'my', 'friend', 'now'], '.', 'meet'),
('junior', 'You help my friend after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'help', 'my', 'friend', 'after', 'school'], '.', 'help'),
('junior', 'We drink water every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'We take a bus this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'take', 'a', 'bus', 'this', 'morning'], '.', 'take'),
('junior', 'We go to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'We walk to school later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'They go to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'They meet my friend today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'meet', 'my', 'friend', 'today'], '.', 'meet'),
('junior', 'I walk to school after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'walk', 'to', 'school', 'after', 'school'], '.', 'walk'),
('junior', 'I use my phone after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'use', 'my', 'phone', 'after', 'school'], '.', 'use'),
('junior', 'She watch TV today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'watch', 'TV', 'today'], '.', 'watch'),
('junior', 'You walk to school tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'walk', 'to', 'school', 'tonight'], '.', 'walk'),
('junior', 'She go to school later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'go', 'to', 'school', 'later'], '.', 'go'),
('junior', 'You run in the park tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'run', 'in', 'the', 'park', 'tonight'], '.', 'run'),
('junior', 'She drink water every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'They meet my friend later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'meet', 'my', 'friend', 'later'], '.', 'meet'),
('junior', 'They listen to music after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'listen', 'to', 'music', 'after', 'school'], '.', 'listen'),
('junior', 'You go to school every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'go', 'to', 'school', 'every', 'day'], '.', 'go'),
('junior', 'They do my homework after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'do', 'my', 'homework', 'after', 'school'], '.', 'do'),
('junior', 'He study English every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'study', 'English', 'every', 'day'], '.', 'study'),
('junior', 'She drink water every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'She take a bus this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'take', 'a', 'bus', 'this', 'morning'], '.', 'take'),
('junior', 'She run in the park now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'run', 'in', 'the', 'park', 'now'], '.', 'run'),
('junior', 'He meet my friend tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'meet', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'We help my friend this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'help', 'my', 'friend', 'this', 'morning'], '.', 'help'),
('junior', 'We open the door every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'open', 'the', 'door', 'every', 'day'], '.', 'open'),
('junior', 'They meet my friend today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'meet', 'my', 'friend', 'today'], '.', 'meet'),
('junior', 'You drink water tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'drink', 'water', 'tonight'], '.', 'drink'),
('junior', 'She do my homework this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'do', 'my', 'homework', 'this', 'morning'], '.', 'do'),
('junior', 'I listen to music every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I open the door this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'open', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'They watch TV after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'watch', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'They play soccer later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'They open the door after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'open', 'the', 'door', 'after', 'school'], '.', 'open'),
('junior', 'She call my mother today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'call', 'my', 'mother', 'today'], '.', 'call'),
('junior', 'She go to school after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'go', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'They eat lunch tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'eat', 'lunch', 'tonight'], '.', 'eat'),
('junior', 'We go to school after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'go', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'I read a book every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'I read a book every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'We play soccer today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'She open the door tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'I write a message after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'write', 'a', 'message', 'after', 'school'], '.', 'write'),
('junior', 'They call my mother tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'call', 'my', 'mother', 'tonight'], '.', 'call'),
('junior', 'She listen to music tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'listen', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'They eat lunch today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'eat', 'lunch', 'today'], '.', 'eat'),
('junior', 'I use my phone now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'use', 'my', 'phone', 'now'], '.', 'use'),
('junior', 'She play soccer every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'play', 'soccer', 'every', 'day'], '.', 'play'),
('junior', 'She open the door this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'open', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'I play soccer later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'We listen to music this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'listen', 'to', 'music', 'this', 'morning'], '.', 'listen'),
('junior', 'They eat lunch this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'eat', 'lunch', 'this', 'morning'], '.', 'eat'),
('junior', 'He open the door later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'open', 'the', 'door', 'later'], '.', 'open'),
('junior', 'They read a book after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'read', 'a', 'book', 'after', 'school'], '.', 'read'),
('junior', 'I write a message after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'write', 'a', 'message', 'after', 'school'], '.', 'write'),
('junior', 'They drink water today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'drink', 'water', 'today'], '.', 'drink'),
('junior', 'He listen to music today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'listen', 'to', 'music', 'today'], '.', 'listen'),
('junior', 'They call my mother after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'call', 'my', 'mother', 'after', 'school'], '.', 'call'),
('junior', 'They write a message every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'write', 'a', 'message', 'every', 'day'], '.', 'write'),
('junior', 'We drink water after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'drink', 'water', 'after', 'school'], '.', 'drink'),
('junior', 'She walk to school every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'walk', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'He buy some food this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'buy', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'He run in the park after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'run', 'in', 'the', 'park', 'after', 'school'], '.', 'run'),
('junior', 'We play soccer tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'I take a bus after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'take', 'a', 'bus', 'after', 'school'], '.', 'take'),
('junior', 'We open the door tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'I do my homework tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'They call my mother later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'call', 'my', 'mother', 'later'], '.', 'call'),
('junior', 'He clean my room this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'this', 'morning'], '.', 'clean'),
('junior', 'She walk to school today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'walk', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'They walk to school every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'walk', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'You watch TV this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'watch', 'TV', 'this', 'morning'], '.', 'watch'),
('junior', 'She play soccer today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'I take a bus later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'You write a message tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'write', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'She go to school after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'go', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'He take a bus tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'take', 'a', 'bus', 'tonight'], '.', 'take'),
('junior', 'You write a message tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'write', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'They play soccer later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'They drink water later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'drink', 'water', 'later'], '.', 'drink'),
('junior', 'He meet my friend tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'meet', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'I open the door tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'She watch TV after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'watch', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'He write a message now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'write', 'a', 'message', 'now'], '.', 'write'),
('junior', 'You run in the park every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'run', 'in', 'the', 'park', 'every', 'day'], '.', 'run'),
('junior', 'We call my mother this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'call', 'my', 'mother', 'this', 'morning'], '.', 'call'),
('junior', 'She eat lunch this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'eat', 'lunch', 'this', 'morning'], '.', 'eat'),
('junior', 'They play soccer today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'You play soccer this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'play', 'soccer', 'this', 'morning'], '.', 'play'),
('junior', 'They open the door later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'open', 'the', 'door', 'later'], '.', 'open'),
('junior', 'He open the door tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'She play soccer tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'He drink water now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'drink', 'water', 'now'], '.', 'drink'),
('junior', 'You listen to music later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'listen', 'to', 'music', 'later'], '.', 'listen'),
('junior', 'I take a bus after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'take', 'a', 'bus', 'after', 'school'], '.', 'take'),
('junior', 'He listen to music tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'listen', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'They eat lunch today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'eat', 'lunch', 'today'], '.', 'eat'),
('junior', 'He do my homework now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'do', 'my', 'homework', 'now'], '.', 'do'),
('junior', 'He buy some food every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'buy', 'some', 'food', 'every', 'day'], '.', 'buy'),
('junior', 'I do my homework every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'do', 'my', 'homework', 'every', 'day'], '.', 'do'),
('junior', 'They play soccer this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'this', 'morning'], '.', 'play'),
('junior', 'I drink water now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'drink', 'water', 'now'], '.', 'drink'),
('junior', 'You open the door now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'open', 'the', 'door', 'now'], '.', 'open'),
('junior', 'They play soccer after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'after', 'school'], '.', 'play'),
('junior', 'We read a book now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'read', 'a', 'book', 'now'], '.', 'read'),
('junior', 'I play soccer tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'You take a bus later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'I buy some food tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'He help my friend this morning .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'help', 'my', 'friend', 'this', 'morning'], '.', 'help'),
('junior', 'They clean my room today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'clean', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'They take a bus today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'take', 'a', 'bus', 'today'], '.', 'take'),
('junior', 'You open the door now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'open', 'the', 'door', 'now'], '.', 'open'),
('junior', 'He open the door now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'open', 'the', 'door', 'now'], '.', 'open'),
('junior', 'She watch TV after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'watch', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'You help my friend every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'help', 'my', 'friend', 'every', 'day'], '.', 'help'),
('junior', 'She write a message tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'write', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'He clean my room today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'clean', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'He take a bus every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'take', 'a', 'bus', 'every', 'day'], '.', 'take'),
('junior', 'They open the door after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'open', 'the', 'door', 'after', 'school'], '.', 'open'),
('junior', 'They listen to music every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I drink water every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'We do my homework tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'We call my mother later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'call', 'my', 'mother', 'later'], '.', 'call'),
('junior', 'I clean my room today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'clean', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'She write a message today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['She', 'write', 'a', 'message', 'today'], '.', 'write'),
('junior', 'I play soccer tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'They go to school now .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'go', 'to', 'school', 'now'], '.', 'go'),
('junior', 'He watch TV tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['He', 'watch', 'TV', 'tonight'], '.', 'watch'),
('junior', 'We clean my room after school .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'clean', 'my', 'room', 'after', 'school'], '.', 'clean'),
('junior', 'We study English every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'study', 'English', 'every', 'day'], '.', 'study'),
('junior', 'You read a book every day .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['You', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'We help my friend later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'help', 'my', 'friend', 'later'], '.', 'help'),
('junior', 'They play soccer tonight .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['They', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'I play soccer today .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['I', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'We walk to school later .', 'わたしたちは にちじょうの こうどうを します。', ARRAY['We', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'He am meeting my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'am', 'meeting', 'my', 'now'], '.', '進行形'),
('junior', 'Do They do my homework after school ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'do', 'my', 'homework', 'after', 'school'], '?', '疑問文'),
('junior', 'We am runing in now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'runing', 'in', 'now'], '.', '進行形'),
('junior', 'I am studying English now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'We call my mother yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'call', 'my', 'mother', 'yesterday'], '.', '現在形'),
('junior', 'You can play soccer after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'play', 'soccer', 'after', 'school'], '.', 'can'),
('junior', 'Do She do my homework now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'do', 'my', 'homework', 'now'], '?', '疑問文'),
('junior', 'He clean my room yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'clean', 'my', 'room', 'yesterday'], '.', '過去形'),
('junior', 'They am studying English now .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'You am runing in now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'runing', 'in', 'now'], '.', '進行形'),
('junior', 'You will call my mother tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'call', 'my', 'mother', 'tonight'], '.', 'will'),
('junior', 'He can do my homework this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'do', 'my', 'homework', 'this', 'morning'], '.', 'can'),
('junior', 'You can call my mother now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'call', 'my', 'mother', 'now'], '.', 'can'),
('junior', 'Do You drink water today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'drink', 'water', 'today'], '?', '疑問文'),
('junior', 'We play soccer yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'play', 'soccer', 'yesterday'], '.', '過去形'),
('junior', 'Do He buy some food today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'He', 'buy', 'some', 'food', 'today'], '?', '疑問文'),
('junior', 'She go to school yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'go', 'to', 'school', 'yesterday'], '.', '過去形'),
('junior', 'We will watch TV tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'will', 'watch', 'TV', 'tonight'], '.', 'will'),
('junior', 'They call my mother after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'call', 'my', 'mother', 'after', 'school'], '.', '現在形'),
('junior', 'Do You watch TV yesterday ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'watch', 'TV', 'yesterday'], '?', '疑問文'),
('junior', 'He can use my phone every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'use', 'my', 'phone', 'every', 'day'], '.', 'can'),
('junior', 'She will open the door tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'open', 'the', 'door', 'tonight'], '.', 'will'),
('junior', 'They play soccer today .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'play', 'soccer', 'today'], '.', '現在形'),
('junior', 'You listen to music yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'listen', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'You will eat lunch after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'eat', 'lunch', 'after', 'school'], '.', 'will'),
('junior', 'I watch TV yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'watch', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'You listen to music yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'listen', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'I am going to now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'going', 'to', 'now'], '.', '進行形'),
('junior', 'Do She call my mother this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'call', 'my', 'mother', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do You eat lunch this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'eat', 'lunch', 'this', 'morning'], '?', '疑問文'),
('junior', 'He am cleaning my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'am', 'cleaning', 'my', 'now'], '.', '進行形'),
('junior', 'I write a message tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'write', 'a', 'message', 'tonight'], '.', '現在形'),
('junior', 'He will do my homework every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'will', 'do', 'my', 'homework', 'every', 'day'], '.', 'will'),
('junior', 'You clean my room later .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'clean', 'my', 'room', 'later'], '.', '現在形'),
('junior', 'I can take a bus this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'can', 'take', 'a', 'bus', 'this', 'morning'], '.', 'can'),
('junior', 'You drink water later .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'drink', 'water', 'later'], '.', '現在形'),
('junior', 'Do She buy some food later ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'buy', 'some', 'food', 'later'], '?', '疑問文'),
('junior', 'Do She use my phone this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'use', 'my', 'phone', 'this', 'morning'], '?', '疑問文'),
('junior', 'I will buy some food this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'buy', 'some', 'food', 'this', 'morning'], '.', 'will'),
('junior', 'They can take a bus yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'can', 'take', 'a', 'bus', 'yesterday'], '.', 'can'),
('junior', 'You read a book yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'read', 'a', 'book', 'yesterday'], '.', '過去形'),
('junior', 'You will help my friend every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'help', 'my', 'friend', 'every', 'day'], '.', 'will'),
('junior', 'You eat lunch after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'eat', 'lunch', 'after', 'school'], '.', '現在形'),
('junior', 'Do She go to school yesterday ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'We can take a bus yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'take', 'a', 'bus', 'yesterday'], '.', 'can'),
('junior', 'She can drink water yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'can', 'drink', 'water', 'yesterday'], '.', 'can'),
('junior', 'Do I use my phone this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'use', 'my', 'phone', 'this', 'morning'], '?', '疑問文'),
('junior', 'We will listen to music later .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'will', 'listen', 'to', 'music', 'later'], '.', 'will'),
('junior', 'I am cleaning my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'cleaning', 'my', 'now'], '.', '進行形'),
('junior', 'Do You read a book after school ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'read', 'a', 'book', 'after', 'school'], '?', '疑問文'),
('junior', 'He can listen to music later .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'listen', 'to', 'music', 'later'], '.', 'can'),
('junior', 'I open the door yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'open', 'the', 'door', 'yesterday'], '.', '過去形'),
('junior', 'He can drink water after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'drink', 'water', 'after', 'school'], '.', 'can'),
('junior', 'Do He write a message every day ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'He', 'write', 'a', 'message', 'every', 'day'], '?', '疑問文'),
('junior', 'I will do my homework today .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'do', 'my', 'homework', 'today'], '.', 'will'),
('junior', 'They do my homework every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'do', 'my', 'homework', 'every', 'day'], '.', '現在形'),
('junior', 'We eat lunch yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'eat', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'We am going to now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'going', 'to', 'now'], '.', '進行形'),
('junior', 'Do They meet my friend tonight ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'meet', 'my', 'friend', 'tonight'], '?', '疑問文'),
('junior', 'Do They buy some food now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'buy', 'some', 'food', 'now'], '?', '疑問文'),
('junior', 'He watch TV every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'watch', 'TV', 'every', 'day'], '.', '現在形'),
('junior', 'They will listen to music every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'will', 'listen', 'to', 'music', 'every', 'day'], '.', 'will'),
('junior', 'They play soccer this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'play', 'soccer', 'this', 'morning'], '.', '現在形'),
('junior', 'We clean my room later .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'clean', 'my', 'room', 'later'], '.', '現在形'),
('junior', 'Do You call my mother this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'call', 'my', 'mother', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do He help my friend today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'He', 'help', 'my', 'friend', 'today'], '?', '疑問文'),
('junior', 'You do my homework now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'do', 'my', 'homework', 'now'], '.', '現在形'),
('junior', 'He watch TV yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'watch', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'I write a message yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'write', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'We will write a message after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'will', 'write', 'a', 'message', 'after', 'school'], '.', 'will'),
('junior', 'Do You play soccer every day ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'play', 'soccer', 'every', 'day'], '?', '疑問文'),
('junior', 'I can clean my room this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'can', 'clean', 'my', 'room', 'this', 'morning'], '.', 'can'),
('junior', 'I am studying English now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'He write a message yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'write', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'She open the door yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'open', 'the', 'door', 'yesterday'], '.', '過去形'),
('junior', 'He will watch TV this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'will', 'watch', 'TV', 'this', 'morning'], '.', 'will'),
('junior', 'You am studying English now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'You write a message yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'write', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'I will write a message today .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'write', 'a', 'message', 'today'], '.', 'will'),
('junior', 'We help my friend today .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'help', 'my', 'friend', 'today'], '.', '現在形'),
('junior', 'They am reading a now .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'am', 'reading', 'a', 'now'], '.', '進行形'),
('junior', 'He meet my friend yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'meet', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'I am cleaning my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'cleaning', 'my', 'now'], '.', '進行形'),
('junior', 'They drink water yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'drink', 'water', 'yesterday'], '.', '過去形'),
('junior', 'I am buying some now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'buying', 'some', 'now'], '.', '進行形'),
('junior', 'Do You walk to school now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'walk', 'to', 'school', 'now'], '?', '疑問文'),
('junior', 'You can study English tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'study', 'English', 'tonight'], '.', 'can'),
('junior', 'He meet my friend yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'meet', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'She am buying some now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'am', 'buying', 'some', 'now'], '.', '進行形'),
('junior', 'Do You meet my friend after school ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'meet', 'my', 'friend', 'after', 'school'], '?', '疑問文'),
('junior', 'Do They buy some food after school ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'buy', 'some', 'food', 'after', 'school'], '?', '疑問文'),
('junior', 'You will buy some food yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'buy', 'some', 'food', 'yesterday'], '.', 'will'),
('junior', 'She am reading a now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'am', 'reading', 'a', 'now'], '.', '進行形'),
('junior', 'They will listen to music yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'will', 'listen', 'to', 'music', 'yesterday'], '.', 'will'),
('junior', 'You am drinking water now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'They drink water yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'drink', 'water', 'yesterday'], '.', '過去形'),
('junior', 'You read a book yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'read', 'a', 'book', 'yesterday'], '.', '過去形'),
('junior', 'Do They watch TV every day ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'watch', 'TV', 'every', 'day'], '?', '疑問文'),
('junior', 'Do I go to school yesterday ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'She am writeing a now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'am', 'writeing', 'a', 'now'], '.', '進行形'),
('junior', 'He will help my friend yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'will', 'help', 'my', 'friend', 'yesterday'], '.', 'will'),
('junior', 'I will read a book this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'read', 'a', 'book', 'this', 'morning'], '.', 'will'),
('junior', 'I study English yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'study', 'English', 'yesterday'], '.', '過去形'),
('junior', 'She play soccer now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'play', 'soccer', 'now'], '.', '現在形'),
('junior', 'Do We watch TV now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'We', 'watch', 'TV', 'now'], '?', '疑問文'),
('junior', 'We can use my phone every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'use', 'my', 'phone', 'every', 'day'], '.', 'can'),
('junior', 'He am runing in now .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'am', 'runing', 'in', 'now'], '.', '進行形'),
('junior', 'I go to school yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'go', 'to', 'school', 'yesterday'], '.', '過去形'),
('junior', 'We meet my friend yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'meet', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'I will meet my friend tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'meet', 'my', 'friend', 'tonight'], '.', 'will'),
('junior', 'We can write a message after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'write', 'a', 'message', 'after', 'school'], '.', 'can'),
('junior', 'We run in the park yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'run', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'I am listening to now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'listening', 'to', 'now'], '.', '進行形'),
('junior', 'You can help my friend every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'help', 'my', 'friend', 'every', 'day'], '.', 'can'),
('junior', 'He run in the park yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'run', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'I will clean my room this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'clean', 'my', 'room', 'this', 'morning'], '.', 'will'),
('junior', 'They can drink water today .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'can', 'drink', 'water', 'today'], '.', 'can'),
('junior', 'We will write a message now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'will', 'write', 'a', 'message', 'now'], '.', 'will'),
('junior', 'We can read a book this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'read', 'a', 'book', 'this', 'morning'], '.', 'can'),
('junior', 'She use my phone later .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'use', 'my', 'phone', 'later'], '.', '現在形'),
('junior', 'She will drink water tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'drink', 'water', 'tonight'], '.', 'will'),
('junior', 'He go to school today .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'go', 'to', 'school', 'today'], '.', '現在形'),
('junior', 'They will meet my friend this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'will', 'meet', 'my', 'friend', 'this', 'morning'], '.', 'will'),
('junior', 'We can read a book this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'read', 'a', 'book', 'this', 'morning'], '.', 'can'),
('junior', 'They clean my room yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'clean', 'my', 'room', 'yesterday'], '.', '過去形'),
('junior', 'I take a bus yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'take', 'a', 'bus', 'yesterday'], '.', '過去形'),
('junior', 'He listen to music every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'listen', 'to', 'music', 'every', 'day'], '.', '現在形'),
('junior', 'She eat lunch now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'eat', 'lunch', 'now'], '.', '現在形'),
('junior', 'They write a message this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'write', 'a', 'message', 'this', 'morning'], '.', '現在形'),
('junior', 'I can clean my room yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'can', 'clean', 'my', 'room', 'yesterday'], '.', 'can'),
('junior', 'We can do my homework now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'do', 'my', 'homework', 'now'], '.', 'can'),
('junior', 'Do I study English this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'study', 'English', 'this', 'morning'], '?', '疑問文'),
('junior', 'You can run in the park tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'run', 'in', 'the', 'park', 'tonight'], '.', 'can'),
('junior', 'She will meet my friend today .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'today'], '.', 'will'),
('junior', 'I am playing soccer now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'You am helping my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'helping', 'my', 'now'], '.', '進行形'),
('junior', 'Do I watch TV today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'watch', 'TV', 'today'], '?', '疑問文'),
('junior', 'Do He read a book this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'He', 'read', 'a', 'book', 'this', 'morning'], '?', '疑問文'),
('junior', 'You am opening the now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'opening', 'the', 'now'], '.', '進行形'),
('junior', 'We can listen to music this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'can', 'listen', 'to', 'music', 'this', 'morning'], '.', 'can'),
('junior', 'They will do my homework yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'will', 'do', 'my', 'homework', 'yesterday'], '.', 'will'),
('junior', 'They will take a bus today .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'will', 'take', 'a', 'bus', 'today'], '.', 'will'),
('junior', 'You will do my homework after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'do', 'my', 'homework', 'after', 'school'], '.', 'will'),
('junior', 'She eat lunch yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'eat', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'He will study English later .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'will', 'study', 'English', 'later'], '.', 'will'),
('junior', 'Do They buy some food this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'buy', 'some', 'food', 'this', 'morning'], '?', '疑問文'),
('junior', 'He can go to school tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'go', 'to', 'school', 'tonight'], '.', 'can'),
('junior', 'I read a book now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'read', 'a', 'book', 'now'], '.', '現在形'),
('junior', 'You can walk to school every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'walk', 'to', 'school', 'every', 'day'], '.', 'can'),
('junior', 'We am writeing a now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'writeing', 'a', 'now'], '.', '進行形'),
('junior', 'They am helping my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'am', 'helping', 'my', 'now'], '.', '進行形'),
('junior', 'She eat lunch yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'eat', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'We am playing soccer now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Do He help my friend this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'He', 'help', 'my', 'friend', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do She eat lunch yesterday ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'eat', 'lunch', 'yesterday'], '?', '疑問文'),
('junior', 'She do my homework yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'do', 'my', 'homework', 'yesterday'], '.', '過去形'),
('junior', 'Do They play soccer now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'play', 'soccer', 'now'], '?', '疑問文'),
('junior', 'You am cleaning my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'cleaning', 'my', 'now'], '.', '進行形'),
('junior', 'I am runing in now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'runing', 'in', 'now'], '.', '進行形'),
('junior', 'Do We do my homework this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'We', 'do', 'my', 'homework', 'this', 'morning'], '?', '疑問文'),
('junior', 'I am meeting my now .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'am', 'meeting', 'my', 'now'], '.', '進行形'),
('junior', 'We am playing soccer now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Do You play soccer tonight ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'play', 'soccer', 'tonight'], '?', '疑問文'),
('junior', 'We meet my friend today .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'meet', 'my', 'friend', 'today'], '.', '現在形'),
('junior', 'Do I listen to music later ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'listen', 'to', 'music', 'later'], '?', '疑問文'),
('junior', 'Do She use my phone today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'She', 'use', 'my', 'phone', 'today'], '?', '疑問文'),
('junior', 'You am drinking water now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'He can run in the park later .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'can', 'run', 'in', 'the', 'park', 'later'], '.', 'can'),
('junior', 'You will help my friend after school .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'help', 'my', 'friend', 'after', 'school'], '.', 'will'),
('junior', 'I will use my phone every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'will', 'use', 'my', 'phone', 'every', 'day'], '.', 'will'),
('junior', 'He am listening to now .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'am', 'listening', 'to', 'now'], '.', '進行形'),
('junior', 'I use my phone yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['I', 'use', 'my', 'phone', 'yesterday'], '.', '過去形'),
('junior', 'We listen to music yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'listen', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'Do You go to school yesterday ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'You', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'He take a bus yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'take', 'a', 'bus', 'yesterday'], '.', '過去形'),
('junior', 'She will meet my friend this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'this', 'morning'], '.', 'will'),
('junior', 'She am opening the now .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'am', 'opening', 'the', 'now'], '.', '進行形'),
('junior', 'She will take a bus later .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'take', 'a', 'bus', 'later'], '.', 'will'),
('junior', 'Do We study English now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'We', 'study', 'English', 'now'], '?', '疑問文'),
('junior', 'He listen to music yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'listen', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'We am studying English now .', 'にちじょうの えいごれんしゅうです。', ARRAY['We', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'Do They go to school now ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'go', 'to', 'school', 'now'], '?', '疑問文'),
('junior', 'He will write a message today .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'will', 'write', 'a', 'message', 'today'], '.', 'will'),
('junior', 'She can meet my friend every day .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'can', 'meet', 'my', 'friend', 'every', 'day'], '.', 'can'),
('junior', 'You can do my homework later .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'do', 'my', 'homework', 'later'], '.', 'can'),
('junior', 'You can watch TV yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'watch', 'TV', 'yesterday'], '.', 'can'),
('junior', 'You will walk to school now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'will', 'walk', 'to', 'school', 'now'], '.', 'will'),
('junior', 'They can eat lunch this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'can', 'eat', 'lunch', 'this', 'morning'], '.', 'can'),
('junior', 'You can clean my room this morning .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'can', 'clean', 'my', 'room', 'this', 'morning'], '.', 'can'),
('junior', 'Do They call my mother today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'call', 'my', 'mother', 'today'], '?', '疑問文'),
('junior', 'He run in the park yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'run', 'in', 'the', 'park', 'yesterday'], '.', '現在形'),
('junior', 'You write a message yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'write', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'He run in the park yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'run', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'He watch TV yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['He', 'watch', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'She will take a bus tonight .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'take', 'a', 'bus', 'tonight'], '.', 'will'),
('junior', 'You am drinking water now .', 'にちじょうの えいごれんしゅうです。', ARRAY['You', 'am', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'She will meet my friend yesterday .', 'にちじょうの えいごれんしゅうです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'yesterday'], '.', 'will'),
('junior', 'They am playing soccer now .', 'にちじょうの えいごれんしゅうです。', ARRAY['They', 'am', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Do They listen to music this morning ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'They', 'listen', 'to', 'music', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do I call my mother today ?', 'にちじょうの えいごれんしゅうです。', ARRAY['Do', 'I', 'call', 'my', 'mother', 'today'], '?', '疑問文');
