-- ============================================================
-- 単語マスタ シードデータ
-- baby: 50語 / elementary: 100語 / junior: 100語 /
-- high: 80語 / toeic: 70語  合計: 400語
-- ============================================================

INSERT INTO words (level, word, meaning, part_of_speech) VALUES

-- ============================================================
-- BABY（2〜5歳）: 50語
-- ============================================================
-- 動物
('baby', 'cat',      'ねこ',           'n.'),
('baby', 'dog',      'いぬ',           'n.'),
('baby', 'bird',     'とり',           'n.'),
('baby', 'fish',     'さかな',         'n.'),
('baby', 'rabbit',   'うさぎ',         'n.'),
('baby', 'bear',     'くま',           'n.'),
('baby', 'elephant', 'ぞう',           'n.'),
('baby', 'lion',     'らいおん',       'n.'),
('baby', 'monkey',   'さる',           'n.'),
('baby', 'duck',     'あひる',         'n.'),
('baby', 'cow',      'うし',           'n.'),
('baby', 'pig',      'ぶた',           'n.'),
('baby', 'horse',    'うま',           'n.'),
('baby', 'frog',     'かえる',         'n.'),
-- 色
('baby', 'red',      'あか',           'adj.'),
('baby', 'blue',     'あお',           'adj.'),
('baby', 'green',    'みどり',         'adj.'),
('baby', 'yellow',   'きいろ',         'adj.'),
('baby', 'orange',   'オレンジ',       'adj.'),
('baby', 'pink',     'ピンク',         'adj.'),
('baby', 'white',    'しろ',           'adj.'),
('baby', 'black',    'くろ',           'adj.'),
('baby', 'brown',    'ちゃいろ',       'adj.'),
-- 食べ物
('baby', 'apple',    'りんご',         'n.'),
('baby', 'banana',   'バナナ',         'n.'),
('baby', 'milk',     'ぎゅうにゅう',   'n.'),
('baby', 'juice',    'ジュース',       'n.'),
('baby', 'bread',    'パン',           'n.'),
('baby', 'egg',      'たまご',         'n.'),
('baby', 'water',    'みず',           'n.'),
('baby', 'cake',     'ケーキ',         'n.'),
('baby', 'rice',     'ごはん',         'n.'),
('baby', 'cookie',   'クッキー',       'n.'),
-- からだ
('baby', 'eye',      'め',             'n.'),
('baby', 'ear',      'みみ',           'n.'),
('baby', 'nose',     'はな',           'n.'),
('baby', 'mouth',    'くち',           'n.'),
('baby', 'hand',     'て',             'n.'),
('baby', 'foot',     'あし',           'n.'),
-- 家族・人
('baby', 'mom',      'おかあさん',     'n.'),
('baby', 'dad',      'おとうさん',     'n.'),
('baby', 'baby',     'あかちゃん',     'n.'),
('baby', 'boy',      'おとこのこ',     'n.'),
('baby', 'girl',     'おんなのこ',     'n.'),
-- 動作
('baby', 'eat',      'たべる',         'v.'),
('baby', 'drink',    'のむ',           'v.'),
('baby', 'play',     'あそぶ',         'v.'),
('baby', 'sleep',    'ねる',           'v.'),
('baby', 'run',      'はしる',         'v.'),
('baby', 'jump',     'とぶ',           'v.'),

-- ============================================================
-- ELEMENTARY（小学生）: 100語
-- ============================================================
-- 学校
('elementary', 'school',    '学校',       'n.'),
('elementary', 'teacher',   '先生',       'n.'),
('elementary', 'student',   '生徒',       'n.'),
('elementary', 'book',      '本',         'n.'),
('elementary', 'pencil',    'えんぴつ',   'n.'),
('elementary', 'desk',      '机',         'n.'),
('elementary', 'class',     'クラス',     'n.'),
('elementary', 'test',      'テスト',     'n.'),
('elementary', 'homework',  '宿題',       'n.'),
('elementary', 'bag',       'かばん',     'n.'),
-- 教科
('elementary', 'math',      '算数',       'n.'),
('elementary', 'science',   '理科',       'n.'),
('elementary', 'music',     '音楽',       'n.'),
('elementary', 'art',       '図工',       'n.'),
('elementary', 'English',   '英語',       'n.'),
('elementary', 'Japanese',  '国語',       'n.'),
('elementary', 'history',   '歴史',       'n.'),
-- 時間
('elementary', 'morning',   '朝',         'n.'),
('elementary', 'afternoon', '午後',       'n.'),
('elementary', 'evening',   '夕方',       'n.'),
('elementary', 'night',     '夜',         'n.'),
('elementary', 'today',     '今日',       'n.'),
('elementary', 'tomorrow',  '明日',       'n.'),
('elementary', 'yesterday', '昨日',       'n.'),
('elementary', 'week',      '週',         'n.'),
('elementary', 'month',     '月',         'n.'),
('elementary', 'year',      '年',         'n.'),
-- 体
('elementary', 'head',      '頭',         'n.'),
('elementary', 'face',      '顔',         'n.'),
('elementary', 'arm',       '腕',         'n.'),
('elementary', 'leg',       '足',         'n.'),
('elementary', 'finger',    '指',         'n.'),
('elementary', 'tooth',     '歯',         'n.'),
-- 天気
('elementary', 'sunny',     '晴れの',     'adj.'),
('elementary', 'cloudy',    '曇りの',     'adj.'),
('elementary', 'rainy',     '雨の',       'adj.'),
('elementary', 'snowy',     '雪の',       'adj.'),
('elementary', 'windy',     '風の強い',   'adj.'),
('elementary', 'hot',       '暑い',       'adj.'),
('elementary', 'cold',      '寒い',       'adj.'),
('elementary', 'warm',      '暖かい',     'adj.'),
-- スポーツ・趣味
('elementary', 'soccer',    'サッカー',   'n.'),
('elementary', 'baseball',  '野球',       'n.'),
('elementary', 'basketball','バスケットボール', 'n.'),
('elementary', 'swimming',  '水泳',       'n.'),
('elementary', 'tennis',    'テニス',     'n.'),
('elementary', 'cooking',   '料理',       'n.'),
('elementary', 'reading',   '読書',       'n.'),
('elementary', 'drawing',   '絵を描くこと', 'n.'),
-- 形容詞
('elementary', 'big',       '大きい',     'adj.'),
('elementary', 'small',     '小さい',     'adj.'),
('elementary', 'tall',      '背が高い',   'adj.'),
('elementary', 'short',     '短い・低い', 'adj.'),
('elementary', 'fast',      '速い',       'adj.'),
('elementary', 'slow',      '遅い',       'adj.'),
('elementary', 'old',       '古い・年とった', 'adj.'),
('elementary', 'new',       '新しい',     'adj.'),
('elementary', 'happy',     '幸せな',     'adj.'),
('elementary', 'sad',       '悲しい',     'adj.'),
('elementary', 'angry',     '怒った',     'adj.'),
('elementary', 'tired',     '疲れた',     'adj.'),
('elementary', 'hungry',    'おなかがすいた', 'adj.'),
('elementary', 'busy',      '忙しい',     'adj.'),
('elementary', 'cute',      'かわいい',   'adj.'),
('elementary', 'kind',      '親切な',     'adj.'),
('elementary', 'strong',    '強い',       'adj.'),
-- 動詞
('elementary', 'go',        '行く',       'v.'),
('elementary', 'come',      '来る',       'v.'),
('elementary', 'study',     '勉強する',   'v.'),
('elementary', 'read',      '読む',       'v.'),
('elementary', 'write',     '書く',       'v.'),
('elementary', 'walk',      '歩く',       'v.'),
('elementary', 'swim',      '泳ぐ',       'v.'),
('elementary', 'cook',      '料理する',   'v.'),
('elementary', 'buy',       '買う',       'v.'),
('elementary', 'sell',      '売る',       'v.'),
('elementary', 'help',      '手伝う',     'v.'),
('elementary', 'like',      '好きだ',     'v.'),
('elementary', 'love',      '愛する',     'v.'),
('elementary', 'want',      '欲しい',     'v.'),
('elementary', 'have',      '持っている', 'v.'),
('elementary', 'know',      '知っている', 'v.'),
('elementary', 'see',       '見る',       'v.'),
('elementary', 'hear',      '聞こえる',   'v.'),
('elementary', 'speak',     '話す',       'v.'),
('elementary', 'think',     '思う',       'v.'),
-- 場所・乗り物
('elementary', 'park',      '公園',       'n.'),
('elementary', 'hospital',  '病院',       'n.'),
('elementary', 'library',   '図書館',     'n.'),
('elementary', 'store',     'お店',       'n.'),
('elementary', 'bus',       'バス',       'n.'),
('elementary', 'train',     '電車',       'n.'),
('elementary', 'car',       '車',         'n.'),
('elementary', 'bike',      '自転車',     'n.'),
-- 家族
('elementary', 'father',    '父',         'n.'),
('elementary', 'mother',    '母',         'n.'),
('elementary', 'brother',   '兄・弟',     'n.'),
('elementary', 'sister',    '姉・妹',     'n.'),
('elementary', 'friend',    '友達',       'n.'),
('elementary', 'family',    '家族',       'n.'),

-- ============================================================
-- JUNIOR（中学生）: 100語
-- ============================================================
-- 社会・文化
('junior', 'culture',       '文化',       'n.'),
('junior', 'tradition',     '伝統',       'n.'),
('junior', 'society',       '社会',       'n.'),
('junior', 'history',       '歴史',       'n.'),
('junior', 'environment',   '環境',       'n.'),
('junior', 'technology',    '技術',       'n.'),
('junior', 'information',   '情報',       'n.'),
('junior', 'education',     '教育',       'n.'),
('junior', 'government',    '政府',       'n.'),
('junior', 'community',     '地域・コミュニティ', 'n.'),
-- 旅行
('junior', 'airport',       '空港',       'n.'),
('junior', 'hotel',         'ホテル',     'n.'),
('junior', 'station',       '駅',         'n.'),
('junior', 'ticket',        'チケット',   'n.'),
('junior', 'passport',      'パスポート', 'n.'),
('junior', 'reservation',   '予約',       'n.'),
('junior', 'departure',     '出発',       'n.'),
('junior', 'arrival',       '到着',       'n.'),
('junior', 'tourist',       '観光客',     'n.'),
('junior', 'destination',   '目的地',     'n.'),
-- コミュニケーション
('junior', 'message',       'メッセージ', 'n.'),
('junior', 'interview',     '面接・インタビュー', 'n.'),
('junior', 'speech',        'スピーチ',   'n.'),
('junior', 'discussion',    '話し合い',   'n.'),
('junior', 'opinion',       '意見',       'n.'),
('junior', 'agree',         '賛成する',   'v.'),
('junior', 'disagree',      '反対する',   'v.'),
('junior', 'understand',    '理解する',   'v.'),
('junior', 'explain',       '説明する',   'v.'),
('junior', 'introduce',     '紹介する',   'v.'),
-- 自然・環境
('junior', 'forest',        '森',         'n.'),
('junior', 'ocean',         '海',         'n.'),
('junior', 'mountain',      '山',         'n.'),
('junior', 'river',         '川',         'n.'),
('junior', 'island',        '島',         'n.'),
('junior', 'climate',       '気候',       'n.'),
('junior', 'pollution',     '汚染',       'n.'),
('junior', 'energy',        'エネルギー', 'n.'),
('junior', 'recycle',       'リサイクルする', 'v.'),
('junior', 'protect',       '守る',       'v.'),
-- 形容詞
('junior', 'important',     '重要な',     'adj.'),
('junior', 'necessary',     '必要な',     'adj.'),
('junior', 'possible',      '可能な',     'adj.'),
('junior', 'difficult',     '難しい',     'adj.'),
('junior', 'comfortable',   '快適な',     'adj.'),
('junior', 'dangerous',     '危険な',     'adj.'),
('junior', 'expensive',     '高価な',     'adj.'),
('junior', 'famous',        '有名な',     'adj.'),
('junior', 'traditional',   '伝統的な',   'adj.'),
('junior', 'modern',        '現代の',     'adj.'),
('junior', 'international', '国際的な',   'adj.'),
('junior', 'natural',       '自然の',     'adj.'),
-- 動詞
('junior', 'decide',        '決める',     'v.'),
('junior', 'promise',       '約束する',   'v.'),
('junior', 'suggest',       '提案する',   'v.'),
('junior', 'improve',       '改善する',   'v.'),
('junior', 'develop',       '発達させる', 'v.'),
('junior', 'support',       '支える',     'v.'),
('junior', 'produce',       '生産する',   'v.'),
('junior', 'discover',      '発見する',   'v.'),
('junior', 'reduce',        '減らす',     'v.'),
('junior', 'continue',      '続ける',     'v.'),
('junior', 'remember',      '覚えている', 'v.'),
('junior', 'forget',        '忘れる',     'v.'),
('junior', 'practice',      '練習する',   'v.'),
('junior', 'prepare',       '準備する',   'v.'),
('junior', 'achieve',       '達成する',   'v.'),
-- 副詞・接続詞
('junior', 'however',       'しかしながら', 'adv.'),
('junior', 'therefore',     'それゆえ',   'adv.'),
('junior', 'moreover',      'さらに',     'adv.'),
('junior', 'although',      '〜だけれども', 'conj.'),
('junior', 'unless',        '〜でない限り', 'conj.'),
('junior', 'whether',       '〜かどうか', 'conj.'),
-- 名詞
('junior', 'problem',       '問題',       'n.'),
('junior', 'solution',      '解決策',     'n.'),
('junior', 'reason',        '理由',       'n.'),
('junior', 'result',        '結果',       'n.'),
('junior', 'experience',    '経験',       'n.'),
('junior', 'opportunity',   '機会',       'n.'),
('junior', 'challenge',     '挑戦',       'n.'),
('junior', 'mistake',       '間違い',     'n.'),
('junior', 'success',       '成功',       'n.'),
('junior', 'future',        '未来',       'n.'),
('junior', 'dream',         '夢',         'n.'),
('junior', 'goal',          '目標',       'n.'),
('junior', 'effort',        '努力',       'n.'),
('junior', 'ability',       '能力',       'n.'),
('junior', 'knowledge',     '知識',       'n.'),
-- 健康・医療
('junior', 'hospital',      '病院',       'n.'),
('junior', 'medicine',      '薬',         'n.'),
('junior', 'health',        '健康',       'n.'),
('junior', 'exercise',      '運動',       'n.'),
('junior', 'stress',        'ストレス',   'n.'),

-- ============================================================
-- HIGH（高校生）: 80語
-- ============================================================
-- 学術語彙
('high', 'analyze',         '分析する',   'v.'),
('high', 'evaluate',        '評価する',   'v.'),
('high', 'indicate',        '示す',       'v.'),
('high', 'demonstrate',     '証明する',   'v.'),
('high', 'investigate',     '調査する',   'v.'),
('high', 'interpret',       '解釈する',   'v.'),
('high', 'justify',         '正当化する', 'v.'),
('high', 'maintain',        '主張する・維持する', 'v.'),
('high', 'perceive',        '認識する',   'v.'),
('high', 'propose',         '提案する',   'v.'),
('high', 'acknowledge',     '認める',     'v.'),
('high', 'assume',          '仮定する',   'v.'),
('high', 'conclude',        '結論付ける', 'v.'),
('high', 'distinguish',     '区別する',   'v.'),
('high', 'emphasize',       '強調する',   'v.'),
('high', 'facilitate',      '促進する',   'v.'),
('high', 'generate',        '生み出す',   'v.'),
('high', 'implement',       '実施する',   'v.'),
('high', 'minimize',        '最小化する', 'v.'),
('high', 'negotiate',       '交渉する',   'v.'),
('high', 'sustain',         '持続させる', 'v.'),
('high', 'undermine',       '弱体化させる', 'v.'),
('high', 'utilize',         '利用する',   'v.'),
('high', 'advocate',        '支持する・唱える', 'v.'),
('high', 'contradict',      '矛盾する',   'v.'),
-- 形容詞
('high', 'apparent',        '明らかな',   'adj.'),
('high', 'appropriate',     '適切な',     'adj.'),
('high', 'considerable',    '相当な',     'adj.'),
('high', 'controversial',   '論争的な',   'adj.'),
('high', 'fundamental',     '根本的な',   'adj.'),
('high', 'objective',       '客観的な',   'adj.'),
('high', 'relevant',        '関連する',   'adj.'),
('high', 'significant',     '重要な・著しい', 'adj.'),
('high', 'specific',        '特定の',     'adj.'),
('high', 'sufficient',      '十分な',     'adj.'),
('high', 'theoretical',     '理論的な',   'adj.'),
('high', 'comprehensive',   '包括的な',   'adj.'),
('high', 'contemporary',    '現代の',     'adj.'),
('high', 'diverse',         '多様な',     'adj.'),
('high', 'inevitable',      '避けられない', 'adj.'),
('high', 'rational',        '合理的な',   'adj.'),
('high', 'subjective',      '主観的な',   'adj.'),
('high', 'vulnerable',      '傷つきやすい', 'adj.'),
('high', 'ambiguous',       '曖昧な',     'adj.'),
('high', 'explicit',        '明示的な',   'adj.'),
('high', 'implicit',        '暗示的な',   'adj.'),
-- 名詞
('high', 'phenomenon',      '現象',       'n.'),
('high', 'perspective',     '観点',       'n.'),
('high', 'hypothesis',      '仮説',       'n.'),
('high', 'tendency',        '傾向',       'n.'),
('high', 'consequence',     '結果・影響', 'n.'),
('high', 'circumstance',    '状況・事情', 'n.'),
('high', 'paradox',         'パラドックス', 'n.'),
('high', 'metaphor',        '比喩',       'n.'),
('high', 'ideology',        '思想・イデオロギー', 'n.'),
('high', 'democracy',       '民主主義',   'n.'),
('high', 'globalization',   'グローバル化', 'n.'),
('high', 'innovation',      '革新',       'n.'),
('high', 'sustainability',  '持続可能性', 'n.'),
('high', 'inequality',      '不平等',     'n.'),
('high', 'discrimination',  '差別',       'n.'),
-- フレーズ・副詞
('high', 'nevertheless',    'それにもかかわらず', 'adv.'),
('high', 'furthermore',     'さらに・その上', 'adv.'),
('high', 'consequently',    '結果として', 'adv.'),
('high', 'nonetheless',     'それでもなお', 'adv.'),
('high', 'whereas',         '一方で',     'conj.'),
('high', 'thereby',         'それによって', 'adv.'),
('high', 'henceforth',      '今後は',     'adv.'),
('high', 'albeit',          '〜ではあるが', 'conj.'),
('high', 'inherent',        '本来の・固有の', 'adj.'),
('high', 'profound',        '深い・深刻な', 'adj.'),
('high', 'rhetoric',        '修辞学・言葉の技巧', 'n.'),
('high', 'assertion',       '主張・断言', 'n.'),
('high', 'consensus',       '合意・コンセンサス', 'n.'),
('high', 'ethics',          '倫理',       'n.'),
('high', 'integrity',       '誠実さ・完全性', 'n.'),

-- ============================================================
-- TOEIC（社会人）: 70語
-- ============================================================
-- ビジネス基本
('toeic', 'agenda',         '議題',       'n.'),
('toeic', 'budget',         '予算',       'n.'),
('toeic', 'deadline',       '締め切り',   'n.'),
('toeic', 'invoice',        '請求書',     'n.'),
('toeic', 'revenue',        '収益・売上', 'n.'),
('toeic', 'profit',         '利益',       'n.'),
('toeic', 'expense',        '経費',       'n.'),
('toeic', 'quarterly',      '四半期ごとの', 'adj.'),
('toeic', 'fiscal',         '会計上の',   'adj.'),
('toeic', 'asset',          '資産',       'n.'),
-- 人事・組織
('toeic', 'recruit',        '採用する',   'v.'),
('toeic', 'resign',         '辞職する',   'v.'),
('toeic', 'promote',        '昇進させる', 'v.'),
('toeic', 'retire',         '退職する',   'v.'),
('toeic', 'evaluate',       '評価する',   'v.'),
('toeic', 'performance',    '業績・パフォーマンス', 'n.'),
('toeic', 'salary',         '給与',       'n.'),
('toeic', 'benefit',        '福利厚生・利点', 'n.'),
('toeic', 'department',     '部門・部署', 'n.'),
('toeic', 'headquarters',   '本社・本部', 'n.'),
('toeic', 'subsidiary',     '子会社',     'n.'),
('toeic', 'merger',         '合併',       'n.'),
('toeic', 'acquisition',    '買収',       'n.'),
-- 会議・コミュニケーション
('toeic', 'postpone',       '延期する',   'v.'),
('toeic', 'reschedule',     '予定を変更する', 'v.'),
('toeic', 'correspond',     '対応する・連絡する', 'v.'),
('toeic', 'collaborate',    '協力する',   'v.'),
('toeic', 'coordinate',     '調整する',   'v.'),
('toeic', 'facilitate',     '促進する',   'v.'),
('toeic', 'minutes',        '議事録',     'n.'),
('toeic', 'attendee',       '出席者',     'n.'),
('toeic', 'agenda',         '議題',       'n.'),
('toeic', 'conference',     '会議・学会', 'n.'),
-- プロジェクト管理
('toeic', 'milestone',      'マイルストーン・節目', 'n.'),
('toeic', 'deliverable',    '成果物',     'n.'),
('toeic', 'stakeholder',    '利害関係者', 'n.'),
('toeic', 'timeline',       '時程表',     'n.'),
('toeic', 'priority',       '優先事項',   'n.'),
('toeic', 'objective',      '目標・目的', 'n.'),
('toeic', 'implement',      '実施する',   'v.'),
('toeic', 'monitor',        '監視する',   'v.'),
('toeic', 'allocate',       '割り当てる', 'v.'),
('toeic', 'outsource',      '外注する',   'v.'),
-- 取引・契約
('toeic', 'client',         '顧客・クライアント', 'n.'),
('toeic', 'vendor',         '販売業者',   'n.'),
('toeic', 'supplier',       '供給業者',   'n.'),
('toeic', 'contractor',     '請負業者',   'n.'),
('toeic', 'negotiate',      '交渉する',   'v.'),
('toeic', 'comply',         '従う',       'v.'),
('toeic', 'terminate',      '終了させる', 'v.'),
('toeic', 'renew',          '更新する',   'v.'),
('toeic', 'liability',      '責任・負債', 'n.'),
('toeic', 'clause',         '条項',       'n.'),
-- ビジネス表現
('toeic', 'as per',         '〜に従って', 'phr.'),
('toeic', 'on behalf of',   '〜を代表して', 'phr.'),
('toeic', 'pursuant to',    '〜に従い',   'phr.'),
('toeic', 'with regard to', '〜に関して', 'phr.'),
('toeic', 'at your earliest convenience', 'ご都合のよい時に', 'phr.'),
('toeic', 'be advised',     'ご承知ください', 'phr.'),
('toeic', 'per the agreement', '契約に従い', 'phr.'),
-- 金融・会計
('toeic', 'audit',          '監査',       'n.'),
('toeic', 'transaction',    '取引',       'n.'),
('toeic', 'reimburse',      '払い戻す',   'v.'),
('toeic', 'depreciate',     '減価償却する', 'v.'),
('toeic', 'overhead',       '間接費・諸経費', 'n.'),
('toeic', 'turnover',       '売上高・離職率', 'n.'),
('toeic', 'projection',     '見通し・予測', 'n.'),
('toeic', 'gross',          '総〜・税引き前', 'adj.'),
('toeic', 'net',            '純〜・税引き後', 'adj.'),
('toeic', 'leverage',       '活用する・てこを使う', 'v.')

ON CONFLICT (word, level) DO NOTHING;
