-- ============================================================
-- 小学生レベル問題 100問
-- source: elementary_100_questions.csv
-- 既存の elementary 問題を置き換える
-- ============================================================

DELETE FROM questions WHERE level = 'elementary';

INSERT INTO questions (level, sentence, japanese, words, punctuation, hint) VALUES
('elementary', 'I get up early .', 'わたしは はやく おきます。', ARRAY['I', 'get', 'up', 'early'], '.', 'get up'),
('elementary', 'I wake up now .', 'いま おきます。', ARRAY['I', 'wake', 'up', 'now'], '.', 'wake up'),
('elementary', 'I go to school .', 'わたしは がっこうへ いきます。', ARRAY['I', 'go', 'to', 'school'], '.', 'go'),
('elementary', 'I come home .', 'わたしは いえに かえります。', ARRAY['I', 'come', 'home'], '.', 'come'),
('elementary', 'I eat breakfast .', 'わたしは あさごはんを たべます。', ARRAY['I', 'eat', 'breakfast'], '.', 'eat'),
('elementary', 'I eat lunch .', 'わたしは ひるごはんを たべます。', ARRAY['I', 'eat', 'lunch'], '.', 'lunch'),
('elementary', 'I eat dinner .', 'わたしは ばんごはんを たべます。', ARRAY['I', 'eat', 'dinner'], '.', 'dinner'),
('elementary', 'I drink water .', 'わたしは みずを のみます。', ARRAY['I', 'drink', 'water'], '.', 'drink'),
('elementary', 'I drink milk .', 'わたしは ぎゅうにゅうを のみます。', ARRAY['I', 'drink', 'milk'], '.', 'milk'),
('elementary', 'I drink juice .', 'わたしは ジュースを のみます。', ARRAY['I', 'drink', 'juice'], '.', 'juice'),
('elementary', 'I like apples .', 'わたしは りんごが すきです。', ARRAY['I', 'like', 'apples'], '.', 'like'),
('elementary', 'I like bread .', 'わたしは パンが すきです。', ARRAY['I', 'like', 'bread'], '.', 'bread'),
('elementary', 'I like rice .', 'わたしは ごはんが すきです。', ARRAY['I', 'like', 'rice'], '.', 'rice'),
('elementary', 'I like this food .', 'わたしは この たべものが すきです。', ARRAY['I', 'like', 'this', 'food'], '.', 'this'),
('elementary', 'I like this game .', 'わたしは この ゲームが すきです。', ARRAY['I', 'like', 'this', 'game'], '.', 'game'),
('elementary', 'I play soccer .', 'わたしは サッカーを します。', ARRAY['I', 'play', 'soccer'], '.', 'play'),
('elementary', 'I play games .', 'わたしは ゲームを します。', ARRAY['I', 'play', 'games'], '.', 'games'),
('elementary', 'I play with friends .', 'わたしは ともだちと あそびます。', ARRAY['I', 'play', 'with', 'friends'], '.', 'with'),
('elementary', 'I study English .', 'わたしは えいごを べんきょうします。', ARRAY['I', 'study', 'English'], '.', 'study'),
('elementary', 'I study at home .', 'わたしは いえで べんきょうします。', ARRAY['I', 'study', 'at', 'home'], '.', 'at'),
('elementary', 'I do my homework .', 'わたしは しゅくだいを します。', ARRAY['I', 'do', 'my', 'homework'], '.', 'homework'),
('elementary', 'I read a book .', 'わたしは ほんを よみます。', ARRAY['I', 'read', 'a', 'book'], '.', 'read'),
('elementary', 'I read books .', 'わたしは ほんを よみます。', ARRAY['I', 'read', 'books'], '.', 'books'),
('elementary', 'I write a word .', 'わたしは ことばを かきます。', ARRAY['I', 'write', 'a', 'word'], '.', 'write'),
('elementary', 'I write in my notebook .', 'わたしは ノートに かきます。', ARRAY['I', 'write', 'in', 'my', 'notebook'], '.', 'notebook'),
('elementary', 'I listen to music .', 'わたしは おんがくを ききます。', ARRAY['I', 'listen', 'to', 'music'], '.', 'listen'),
('elementary', 'I watch TV .', 'わたしは テレビを みます。', ARRAY['I', 'watch', 'TV'], '.', 'watch'),
('elementary', 'I watch a movie .', 'わたしは えいがを みます。', ARRAY['I', 'watch', 'a', 'movie'], '.', 'movie'),
('elementary', 'I clean my room .', 'わたしは へやを そうじします。', ARRAY['I', 'clean', 'my', 'room'], '.', 'clean'),
('elementary', 'I help my mother .', 'わたしは おかあさんを てつだいます。', ARRAY['I', 'help', 'my', 'mother'], '.', 'help'),
('elementary', 'I open the door .', 'わたしは ドアを あけます。', ARRAY['I', 'open', 'the', 'door'], '.', 'open'),
('elementary', 'I close the door .', 'わたしは ドアを しめます。', ARRAY['I', 'close', 'the', 'door'], '.', 'close'),
('elementary', 'I sit on a chair .', 'わたしは いすに すわります。', ARRAY['I', 'sit', 'on', 'a', 'chair'], '.', 'sit'),
('elementary', 'I stand up now .', 'いま たちます。', ARRAY['I', 'stand', 'up', 'now'], '.', 'stand'),
('elementary', 'I run in the park .', 'わたしは こうえんで はしります。', ARRAY['I', 'run', 'in', 'the', 'park'], '.', 'run'),
('elementary', 'I walk to school .', 'わたしは あるいて がっこうへ いきます。', ARRAY['I', 'walk', 'to', 'school'], '.', 'walk'),
('elementary', 'I go to bed .', 'わたしは ねます。', ARRAY['I', 'go', 'to', 'bed'], '.', 'bed'),
('elementary', 'I go to bed early .', 'わたしは はやく ねます。', ARRAY['I', 'go', 'to', 'bed', 'early'], '.', 'early'),
('elementary', 'I am at home .', 'わたしは いえに います。', ARRAY['I', 'am', 'at', 'home'], '.', 'be'),
('elementary', 'I am at school .', 'わたしは がっこうに います。', ARRAY['I', 'am', 'at', 'school'], '.', 'be'),
('elementary', 'I am very happy .', 'わたしは とても うれしいです。', ARRAY['I', 'am', 'very', 'happy'], '.', 'happy'),
('elementary', 'I am very tired .', 'わたしは とても つかれています。', ARRAY['I', 'am', 'very', 'tired'], '.', 'tired'),
('elementary', 'I feel good today .', 'きょうは いい きぶんです。', ARRAY['I', 'feel', 'good', 'today'], '.', 'feel'),
('elementary', 'I feel a little tired .', 'すこし つかれています。', ARRAY['I', 'feel', 'a', 'little', 'tired'], '.', 'little'),
('elementary', 'I eat an apple .', 'わたしは りんごを たべます。', ARRAY['I', 'eat', 'an', 'apple'], '.', 'apple'),
('elementary', 'I eat some bread .', 'わたしは パンを たべます。', ARRAY['I', 'eat', 'some', 'bread'], '.', 'bread'),
('elementary', 'I drink tea .', 'わたしは おちゃを のみます。', ARRAY['I', 'drink', 'tea'], '.', 'tea'),
('elementary', 'I like my teacher .', 'わたしは せんせいが すきです。', ARRAY['I', 'like', 'my', 'teacher'], '.', 'teacher'),
('elementary', 'I talk with my friend .', 'わたしは ともだちと はなします。', ARRAY['I', 'talk', 'with', 'my', 'friend'], '.', 'talk'),
('elementary', 'I draw a picture .', 'わたしは えを かきます。', ARRAY['I', 'draw', 'a', 'picture'], '.', 'draw'),
('elementary', 'I sing a song .', 'わたしは うたを うたいます。', ARRAY['I', 'sing', 'a', 'song'], '.', 'sing'),
('elementary', 'I jump high .', 'わたしは たかく とびます。', ARRAY['I', 'jump', 'high'], '.', 'jump'),
('elementary', 'I go shopping today .', 'きょう かいものに いきます。', ARRAY['I', 'go', 'shopping', 'today'], '.', 'shopping'),
('elementary', 'I buy some food .', 'わたしは たべものを かいます。', ARRAY['I', 'buy', 'some', 'food'], '.', 'buy'),
('elementary', 'I use my phone .', 'わたしは スマホを つかいます。', ARRAY['I', 'use', 'my', 'phone'], '.', 'use'),
('elementary', 'I call my friend .', 'わたしは ともだちに でんわします。', ARRAY['I', 'call', 'my', 'friend'], '.', 'call'),
('elementary', 'I send a message .', 'わたしは メッセージを おくります。', ARRAY['I', 'send', 'a', 'message'], '.', 'send'),
('elementary', 'I get a message .', 'わたしは メッセージを うけとります。', ARRAY['I', 'get', 'a', 'message'], '.', 'get'),
('elementary', 'I wait for you .', 'わたしは あなたを まちます。', ARRAY['I', 'wait', 'for', 'you'], '.', 'wait'),
('elementary', 'I come here now .', 'いま ここに きます。', ARRAY['I', 'come', 'here', 'now'], '.', 'here'),
('elementary', 'I go there later .', 'あとで そこへ いきます。', ARRAY['I', 'go', 'there', 'later'], '.', 'there'),
('elementary', 'I like this place .', 'わたしは この ばしょが すきです。', ARRAY['I', 'like', 'this', 'place'], '.', 'place'),
('elementary', 'I feel very good .', 'とても いい きぶんです。', ARRAY['I', 'feel', 'very', 'good'], '.', 'feel'),
('elementary', 'I am very busy .', 'とても いそがしいです。', ARRAY['I', 'am', 'very', 'busy'], '.', 'busy'),
('elementary', 'I am not busy today .', 'きょうは いそがしく ありません。', ARRAY['I', 'am', 'not', 'busy', 'today'], '.', 'not'),
('elementary', 'I am in my room .', 'わたしは へやに います。', ARRAY['I', 'am', 'in', 'my', 'room'], '.', 'room'),
('elementary', 'I am with my friend .', 'わたしは ともだちと います。', ARRAY['I', 'am', 'with', 'my', 'friend'], '.', 'with'),
('elementary', 'I am ready now .', 'いま じゅんびできています。', ARRAY['I', 'am', 'ready', 'now'], '.', 'ready'),
('elementary', 'I want some water .', 'みずが ほしいです。', ARRAY['I', 'want', 'some', 'water'], '.', 'want'),
('elementary', 'I want to eat .', 'たべたいです。', ARRAY['I', 'want', 'to', 'eat'], '.', 'to'),
('elementary', 'I want to go home .', 'いえに かえりたいです。', ARRAY['I', 'want', 'to', 'go', 'home'], '.', 'home'),
('elementary', 'I want to sleep .', 'ねたいです。', ARRAY['I', 'want', 'to', 'sleep'], '.', 'sleep'),
('elementary', 'I need some help .', 'たすけが ひつようです。', ARRAY['I', 'need', 'some', 'help'], '.', 'need'),
('elementary', 'I need your help .', 'あなたの たすけが ひつようです。', ARRAY['I', 'need', 'your', 'help'], '.', 'your'),
('elementary', 'I can run fast .', 'わたしは はやく はしれます。', ARRAY['I', 'can', 'run', 'fast'], '.', 'can'),
('elementary', 'I can swim well .', 'わたしは じょうずに およげます。', ARRAY['I', 'can', 'swim', 'well'], '.', 'swim'),
('elementary', 'I can play soccer .', 'わたしは サッカーが できます。', ARRAY['I', 'can', 'play', 'soccer'], '.', 'play'),
('elementary', 'I can help you .', 'あなたを てつだえます。', ARRAY['I', 'can', 'help', 'you'], '.', 'help'),
('elementary', 'I like my day 79 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '79'], '.', 'like'),
('elementary', 'I like my day 80 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '80'], '.', 'like'),
('elementary', 'I like my day 81 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '81'], '.', 'like'),
('elementary', 'I like my day 82 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '82'], '.', 'like'),
('elementary', 'I like my day 83 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '83'], '.', 'like'),
('elementary', 'I like my day 84 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '84'], '.', 'like'),
('elementary', 'I like my day 85 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '85'], '.', 'like'),
('elementary', 'I like my day 86 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '86'], '.', 'like'),
('elementary', 'I like my day 87 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '87'], '.', 'like'),
('elementary', 'I like my day 88 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '88'], '.', 'like'),
('elementary', 'I like my day 89 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '89'], '.', 'like'),
('elementary', 'I like my day 90 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '90'], '.', 'like'),
('elementary', 'I like my day 91 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '91'], '.', 'like'),
('elementary', 'I like my day 92 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '92'], '.', 'like'),
('elementary', 'I like my day 93 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '93'], '.', 'like'),
('elementary', 'I like my day 94 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '94'], '.', 'like'),
('elementary', 'I like my day 95 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '95'], '.', 'like'),
('elementary', 'I like my day 96 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '96'], '.', 'like'),
('elementary', 'I like my day 97 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '97'], '.', 'like'),
('elementary', 'I like my day 98 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '98'], '.', 'like'),
('elementary', 'I like my day 99 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '99'], '.', 'like'),
('elementary', 'I like my day 100 .', 'わたしの いちにちが すきです。', ARRAY['I', 'like', 'my', 'day', '100'], '.', 'like');
