-- ============================================================
-- ???????? 400?
-- source: junior_200_questions.csv + junior_grammar_200.csv
-- ??? junior ????????
-- obvious grammar fixes applied after import
-- ============================================================

DELETE FROM questions WHERE level = 'junior';

INSERT INTO questions (level, sentence, japanese, words, punctuation, hint) VALUES
('junior', 'They do my homework every day .', 'かれらは 毎日 わたしの 宿題を します。', ARRAY['They', 'do', 'my', 'homework', 'every', 'day'], '.', 'do'),
('junior', 'They buy some food every day .', 'かれらは 毎日 食べ物を 買います。', ARRAY['They', 'buy', 'some', 'food', 'every', 'day'], '.', 'buy'),
('junior', 'I clean my room tonight .', 'わたしは 今夜 わたしの 部屋を そうじします。', ARRAY['I', 'clean', 'my', 'room', 'tonight'], '.', 'clean'),
('junior', 'They call my mother now .', 'かれらは 今 わたしの 母に 電話を します。', ARRAY['They', 'call', 'my', 'mother', 'now'], '.', 'call'),
('junior', 'I go to school today .', 'わたしは 今日 学校へ 行きます。', ARRAY['I', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'We watch TV today .', 'わたしたちは 今日 テレビを 見ます。', ARRAY['We', 'watch', 'TV', 'today'], '.', 'watch'),
('junior', 'They listen to music now .', 'かれらは 今 音楽を 聞きます。', ARRAY['They', 'listen', 'to', 'music', 'now'], '.', 'listen'),
('junior', 'She walks to school today .', 'かのじょは 今日 学校へ 歩いて 行きます。', ARRAY['She', 'walks', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'You study English after school .', 'あなたは 放課後 英語を 勉強します。', ARRAY['You', 'study', 'English', 'after', 'school'], '.', 'study'),
('junior', 'He uses my phone tonight .', 'かれは 今夜 わたしの 電話を 使います。', ARRAY['He', 'uses', 'my', 'phone', 'tonight'], '.', 'use'),
('junior', 'They watch TV later .', 'かれらは あとで テレビを 見ます。', ARRAY['They', 'watch', 'TV', 'later'], '.', 'watch'),
('junior', 'They buy some food now .', 'かれらは 今 食べ物を 買います。', ARRAY['They', 'buy', 'some', 'food', 'now'], '.', 'buy'),
('junior', 'She takes a bus later .', 'かのじょは あとで バスに 乗ります。', ARRAY['She', 'takes', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'They meet my friend tonight .', 'かれらは 今夜 わたしの 友だちに 会います。', ARRAY['They', 'meet', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'You use my phone every day .', 'あなたは 毎日 わたしの 電話を 使います。', ARRAY['You', 'use', 'my', 'phone', 'every', 'day'], '.', 'use'),
('junior', 'You play soccer every day .', 'あなたは 毎日 サッカーを します。', ARRAY['You', 'play', 'soccer', 'every', 'day'], '.', 'play'),
('junior', 'She buys some food this morning .', 'かのじょは 今朝 食べ物を 買います。', ARRAY['She', 'buys', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'We take a bus now .', 'わたしたちは 今 バスに 乗ります。', ARRAY['We', 'take', 'a', 'bus', 'now'], '.', 'take'),
('junior', 'We buy some food tonight .', 'わたしたちは 今夜 食べ物を 買います。', ARRAY['We', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'You eat lunch now .', 'あなたは 今 昼ごはんを 食べます。', ARRAY['You', 'eat', 'lunch', 'now'], '.', 'eat'),
('junior', 'You go to school now .', 'あなたは 今 学校へ 行きます。', ARRAY['You', 'go', 'to', 'school', 'now'], '.', 'go'),
('junior', 'He runs in the park today .', 'かれは 今日 公園で 走ります。', ARRAY['He', 'runs', 'in', 'the', 'park', 'today'], '.', 'run'),
('junior', 'He uses my phone this morning .', 'かれは 今朝 わたしの 電話を 使います。', ARRAY['He', 'uses', 'my', 'phone', 'this', 'morning'], '.', 'use'),
('junior', 'I run in the park this morning .', 'わたしは 今朝 公園で 走ります。', ARRAY['I', 'run', 'in', 'the', 'park', 'this', 'morning'], '.', 'run'),
('junior', 'They run in the park tonight .', 'かれらは 今夜 公園で 走ります。', ARRAY['They', 'run', 'in', 'the', 'park', 'tonight'], '.', 'run'),
('junior', 'She calls my mother tonight .', 'かのじょは 今夜 わたしの 母に 電話を します。', ARRAY['She', 'calls', 'my', 'mother', 'tonight'], '.', 'call'),
('junior', 'You listen to music tonight .', 'あなたは 今夜 音楽を 聞きます。', ARRAY['You', 'listen', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'We use my phone this morning .', 'わたしたちは 今朝 わたしの 電話を 使います。', ARRAY['We', 'use', 'my', 'phone', 'this', 'morning'], '.', 'use'),
('junior', 'We walk to school this morning .', 'わたしたちは 今朝 学校へ 歩いて 行きます。', ARRAY['We', 'walk', 'to', 'school', 'this', 'morning'], '.', 'walk'),
('junior', 'They read a book every day .', 'かれらは 毎日 本を 読みます。', ARRAY['They', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'She goes to school tonight .', 'かのじょは 今夜 学校へ 行きます。', ARRAY['She', 'goes', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'You open the door every day .', 'あなたは 毎日 ドアを 開けます。', ARRAY['You', 'open', 'the', 'door', 'every', 'day'], '.', 'open'),
('junior', 'I open the door this morning .', 'わたしは 今朝 ドアを 開けます。', ARRAY['I', 'open', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'They go to school tonight .', 'かれらは 今夜 学校へ 行きます。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'She walks to school every day .', 'かのじょは 毎日 学校へ 歩いて 行きます。', ARRAY['She', 'walks', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'I do my homework tonight .', 'わたしは 今夜 わたしの 宿題を します。', ARRAY['I', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'I read a book after school .', 'わたしは 放課後 本を 読みます。', ARRAY['I', 'read', 'a', 'book', 'after', 'school'], '.', 'read'),
('junior', 'He reads a book this morning .', 'かれは 今朝 本を 読みます。', ARRAY['He', 'reads', 'a', 'book', 'this', 'morning'], '.', 'read'),
('junior', 'I drink water after school .', 'わたしは 放課後 水を 飲みます。', ARRAY['I', 'drink', 'water', 'after', 'school'], '.', 'drink'),
('junior', 'He cleans my room now .', 'かれは 今 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'now'], '.', 'clean'),
('junior', 'We walk to school today .', 'わたしたちは 今日 学校へ 歩いて 行きます。', ARRAY['We', 'walk', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'You open the door tonight .', 'あなたは 今夜 ドアを 開けます。', ARRAY['You', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'You help my friend every day .', 'あなたは 毎日 わたしの 友だちを 手伝います。', ARRAY['You', 'help', 'my', 'friend', 'every', 'day'], '.', 'help'),
('junior', 'You drink water today .', 'あなたは 今日 水を 飲みます。', ARRAY['You', 'drink', 'water', 'today'], '.', 'drink'),
('junior', 'He cleans my room now .', 'かれは 今 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'now'], '.', 'clean'),
('junior', 'She meets my friend every day .', 'かのじょは 毎日 わたしの 友だちに 会います。', ARRAY['She', 'meets', 'my', 'friend', 'every', 'day'], '.', 'meet'),
('junior', 'You buy some food tonight .', 'あなたは 今夜 食べ物を 買います。', ARRAY['You', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'She buys some food this morning .', 'かのじょは 今朝 食べ物を 買います。', ARRAY['She', 'buys', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'They listen to music every day .', 'かれらは 毎日 音楽を 聞きます。', ARRAY['They', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'They play soccer today .', 'かれらは 今日 サッカーを します。', ARRAY['They', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'You drink water this morning .', 'あなたは 今朝 水を 飲みます。', ARRAY['You', 'drink', 'water', 'this', 'morning'], '.', 'drink'),
('junior', 'He buys some food later .', 'かれは あとで 食べ物を 買います。', ARRAY['He', 'buys', 'some', 'food', 'later'], '.', 'buy'),
('junior', 'I take a bus later .', 'わたしは あとで バスに 乗ります。', ARRAY['I', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'They go to school tonight .', 'かれらは 今夜 学校へ 行きます。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'He plays soccer after school .', 'かれは 放課後 サッカーを します。', ARRAY['He', 'plays', 'soccer', 'after', 'school'], '.', 'play'),
('junior', 'You walk to school later .', 'あなたは あとで 学校へ 歩いて 行きます。', ARRAY['You', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'He listens to music now .', 'かれは 今 音楽を 聞きます。', ARRAY['He', 'listens', 'to', 'music', 'now'], '.', 'listen'),
('junior', 'She eats lunch now .', 'かのじょは 今 昼ごはんを 食べます。', ARRAY['She', 'eats', 'lunch', 'now'], '.', 'eat'),
('junior', 'He cleans my room after school .', 'かれは 放課後 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'after', 'school'], '.', 'clean'),
('junior', 'You use my phone today .', 'あなたは 今日 わたしの 電話を 使います。', ARRAY['You', 'use', 'my', 'phone', 'today'], '.', 'use'),
('junior', 'You listen to music every day .', 'あなたは 毎日 音楽を 聞きます。', ARRAY['You', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I go to school this morning .', 'わたしは 今朝 学校へ 行きます。', ARRAY['I', 'go', 'to', 'school', 'this', 'morning'], '.', 'go'),
('junior', 'He cleans my room this morning .', 'かれは 今朝 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'this', 'morning'], '.', 'clean'),
('junior', 'He goes to school tonight .', 'かれは 今夜 学校へ 行きます。', ARRAY['He', 'goes', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'They go to school tonight .', 'かれらは 今夜 学校へ 行きます。', ARRAY['They', 'go', 'to', 'school', 'tonight'], '.', 'go'),
('junior', 'They meet my friend now .', 'かれらは 今 わたしの 友だちに 会います。', ARRAY['They', 'meet', 'my', 'friend', 'now'], '.', 'meet'),
('junior', 'You help my friend after school .', 'あなたは 放課後 わたしの 友だちを 手伝います。', ARRAY['You', 'help', 'my', 'friend', 'after', 'school'], '.', 'help'),
('junior', 'We drink water every day .', 'わたしたちは 毎日 水を 飲みます。', ARRAY['We', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'We take a bus this morning .', 'わたしたちは 今朝 バスに 乗ります。', ARRAY['We', 'take', 'a', 'bus', 'this', 'morning'], '.', 'take'),
('junior', 'We go to school today .', 'わたしたちは 今日 学校へ 行きます。', ARRAY['We', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'We walk to school later .', 'わたしたちは あとで 学校へ 歩いて 行きます。', ARRAY['We', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'They go to school today .', 'かれらは 今日 学校へ 行きます。', ARRAY['They', 'go', 'to', 'school', 'today'], '.', 'go'),
('junior', 'They meet my friend today .', 'かれらは 今日 わたしの 友だちに 会います。', ARRAY['They', 'meet', 'my', 'friend', 'today'], '.', 'meet'),
('junior', 'I walk to school after school .', 'わたしは 放課後 学校へ 歩いて 行きます。', ARRAY['I', 'walk', 'to', 'school', 'after', 'school'], '.', 'walk'),
('junior', 'I use my phone after school .', 'わたしは 放課後 わたしの 電話を 使います。', ARRAY['I', 'use', 'my', 'phone', 'after', 'school'], '.', 'use'),
('junior', 'She watches TV today .', 'かのじょは 今日 テレビを 見ます。', ARRAY['She', 'watches', 'TV', 'today'], '.', 'watch'),
('junior', 'You walk to school tonight .', 'あなたは 今夜 学校へ 歩いて 行きます。', ARRAY['You', 'walk', 'to', 'school', 'tonight'], '.', 'walk'),
('junior', 'She goes to school later .', 'かのじょは あとで 学校へ 行きます。', ARRAY['She', 'goes', 'to', 'school', 'later'], '.', 'go'),
('junior', 'You run in the park tonight .', 'あなたは 今夜 公園で 走ります。', ARRAY['You', 'run', 'in', 'the', 'park', 'tonight'], '.', 'run'),
('junior', 'She drinks water every day .', 'かのじょは 毎日 水を 飲みます。', ARRAY['She', 'drinks', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'They meet my friend later .', 'かれらは あとで わたしの 友だちに 会います。', ARRAY['They', 'meet', 'my', 'friend', 'later'], '.', 'meet'),
('junior', 'They listen to music after school .', 'かれらは 放課後 音楽を 聞きます。', ARRAY['They', 'listen', 'to', 'music', 'after', 'school'], '.', 'listen'),
('junior', 'You go to school every day .', 'あなたは 毎日 学校へ 行きます。', ARRAY['You', 'go', 'to', 'school', 'every', 'day'], '.', 'go'),
('junior', 'They do my homework after school .', 'かれらは 放課後 わたしの 宿題を します。', ARRAY['They', 'do', 'my', 'homework', 'after', 'school'], '.', 'do'),
('junior', 'He studies English every day .', 'かれは 毎日 英語を 勉強します。', ARRAY['He', 'studies', 'English', 'every', 'day'], '.', 'study'),
('junior', 'She drinks water every day .', 'かのじょは 毎日 水を 飲みます。', ARRAY['She', 'drinks', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'She takes a bus this morning .', 'かのじょは 今朝 バスに 乗ります。', ARRAY['She', 'takes', 'a', 'bus', 'this', 'morning'], '.', 'take'),
('junior', 'She runs in the park now .', 'かのじょは 今 公園で 走ります。', ARRAY['She', 'runs', 'in', 'the', 'park', 'now'], '.', 'run'),
('junior', 'He meets my friend tonight .', 'かれは 今夜 わたしの 友だちに 会います。', ARRAY['He', 'meets', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'We help my friend this morning .', 'わたしたちは 今朝 わたしの 友だちを 手伝います。', ARRAY['We', 'help', 'my', 'friend', 'this', 'morning'], '.', 'help'),
('junior', 'We open the door every day .', 'わたしたちは 毎日 ドアを 開けます。', ARRAY['We', 'open', 'the', 'door', 'every', 'day'], '.', 'open'),
('junior', 'They meet my friend today .', 'かれらは 今日 わたしの 友だちに 会います。', ARRAY['They', 'meet', 'my', 'friend', 'today'], '.', 'meet'),
('junior', 'You drink water tonight .', 'あなたは 今夜 水を 飲みます。', ARRAY['You', 'drink', 'water', 'tonight'], '.', 'drink'),
('junior', 'She does my homework this morning .', 'かのじょは 今朝 わたしの 宿題を します。', ARRAY['She', 'does', 'my', 'homework', 'this', 'morning'], '.', 'do'),
('junior', 'I listen to music every day .', 'わたしは 毎日 音楽を 聞きます。', ARRAY['I', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I open the door this morning .', 'わたしは 今朝 ドアを 開けます。', ARRAY['I', 'open', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'They watch TV after school .', 'かれらは 放課後 テレビを 見ます。', ARRAY['They', 'watch', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'They play soccer later .', 'かれらは あとで サッカーを します。', ARRAY['They', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'They open the door after school .', 'かれらは 放課後 ドアを 開けます。', ARRAY['They', 'open', 'the', 'door', 'after', 'school'], '.', 'open'),
('junior', 'She calls my mother today .', 'かのじょは 今日 わたしの 母に 電話を します。', ARRAY['She', 'calls', 'my', 'mother', 'today'], '.', 'call'),
('junior', 'She goes to school after school .', 'かのじょは 放課後 学校へ 行きます。', ARRAY['She', 'goes', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'They eat lunch tonight .', 'かれらは 今夜 昼ごはんを 食べます。', ARRAY['They', 'eat', 'lunch', 'tonight'], '.', 'eat'),
('junior', 'We go to school after school .', 'わたしたちは 放課後 学校へ 行きます。', ARRAY['We', 'go', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'I read a book every day .', 'わたしは 毎日 本を 読みます。', ARRAY['I', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'I read a book every day .', 'わたしは 毎日 本を 読みます。', ARRAY['I', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'We play soccer today .', 'わたしたちは 今日 サッカーを します。', ARRAY['We', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'She opens the door tonight .', 'かのじょは 今夜 ドアを 開けます。', ARRAY['She', 'opens', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'I write a message after school .', 'わたしは 放課後 メッセージを 書きます。', ARRAY['I', 'write', 'a', 'message', 'after', 'school'], '.', 'write'),
('junior', 'They call my mother tonight .', 'かれらは 今夜 わたしの 母に 電話を します。', ARRAY['They', 'call', 'my', 'mother', 'tonight'], '.', 'call'),
('junior', 'She listens to music tonight .', 'かのじょは 今夜 音楽を 聞きます。', ARRAY['She', 'listens', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'They eat lunch today .', 'かれらは 今日 昼ごはんを 食べます。', ARRAY['They', 'eat', 'lunch', 'today'], '.', 'eat'),
('junior', 'I use my phone now .', 'わたしは 今 わたしの 電話を 使います。', ARRAY['I', 'use', 'my', 'phone', 'now'], '.', 'use'),
('junior', 'She plays soccer every day .', 'かのじょは 毎日 サッカーを します。', ARRAY['She', 'plays', 'soccer', 'every', 'day'], '.', 'play'),
('junior', 'She opens the door this morning .', 'かのじょは 今朝 ドアを 開けます。', ARRAY['She', 'opens', 'the', 'door', 'this', 'morning'], '.', 'open'),
('junior', 'I play soccer later .', 'わたしは あとで サッカーを します。', ARRAY['I', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'We listen to music this morning .', 'わたしたちは 今朝 音楽を 聞きます。', ARRAY['We', 'listen', 'to', 'music', 'this', 'morning'], '.', 'listen'),
('junior', 'They eat lunch this morning .', 'かれらは 今朝 昼ごはんを 食べます。', ARRAY['They', 'eat', 'lunch', 'this', 'morning'], '.', 'eat'),
('junior', 'He opens the door later .', 'かれは あとで ドアを 開けます。', ARRAY['He', 'opens', 'the', 'door', 'later'], '.', 'open'),
('junior', 'They read a book after school .', 'かれらは 放課後 本を 読みます。', ARRAY['They', 'read', 'a', 'book', 'after', 'school'], '.', 'read'),
('junior', 'I write a message after school .', 'わたしは 放課後 メッセージを 書きます。', ARRAY['I', 'write', 'a', 'message', 'after', 'school'], '.', 'write'),
('junior', 'They drink water today .', 'かれらは 今日 水を 飲みます。', ARRAY['They', 'drink', 'water', 'today'], '.', 'drink'),
('junior', 'He listens to music today .', 'かれは 今日 音楽を 聞きます。', ARRAY['He', 'listens', 'to', 'music', 'today'], '.', 'listen'),
('junior', 'They call my mother after school .', 'かれらは 放課後 わたしの 母に 電話を します。', ARRAY['They', 'call', 'my', 'mother', 'after', 'school'], '.', 'call'),
('junior', 'They write a message every day .', 'かれらは 毎日 メッセージを 書きます。', ARRAY['They', 'write', 'a', 'message', 'every', 'day'], '.', 'write'),
('junior', 'We drink water after school .', 'わたしたちは 放課後 水を 飲みます。', ARRAY['We', 'drink', 'water', 'after', 'school'], '.', 'drink'),
('junior', 'She walks to school every day .', 'かのじょは 毎日 学校へ 歩いて 行きます。', ARRAY['She', 'walks', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'He buys some food this morning .', 'かれは 今朝 食べ物を 買います。', ARRAY['He', 'buys', 'some', 'food', 'this', 'morning'], '.', 'buy'),
('junior', 'He runs in the park after school .', 'かれは 放課後 公園で 走ります。', ARRAY['He', 'runs', 'in', 'the', 'park', 'after', 'school'], '.', 'run'),
('junior', 'We play soccer tonight .', 'わたしたちは 今夜 サッカーを します。', ARRAY['We', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'I take a bus after school .', 'わたしは 放課後 バスに 乗ります。', ARRAY['I', 'take', 'a', 'bus', 'after', 'school'], '.', 'take'),
('junior', 'We open the door tonight .', 'わたしたちは 今夜 ドアを 開けます。', ARRAY['We', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'I do my homework tonight .', 'わたしは 今夜 わたしの 宿題を します。', ARRAY['I', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'They call my mother later .', 'かれらは あとで わたしの 母に 電話を します。', ARRAY['They', 'call', 'my', 'mother', 'later'], '.', 'call'),
('junior', 'He cleans my room this morning .', 'かれは 今朝 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'this', 'morning'], '.', 'clean'),
('junior', 'She walks to school today .', 'かのじょは 今日 学校へ 歩いて 行きます。', ARRAY['She', 'walks', 'to', 'school', 'today'], '.', 'walk'),
('junior', 'They walk to school every day .', 'かれらは 毎日 学校へ 歩いて 行きます。', ARRAY['They', 'walk', 'to', 'school', 'every', 'day'], '.', 'walk'),
('junior', 'You watch TV this morning .', 'あなたは 今朝 テレビを 見ます。', ARRAY['You', 'watch', 'TV', 'this', 'morning'], '.', 'watch'),
('junior', 'She plays soccer today .', 'かのじょは 今日 サッカーを します。', ARRAY['She', 'plays', 'soccer', 'today'], '.', 'play'),
('junior', 'I take a bus later .', 'わたしは あとで バスに 乗ります。', ARRAY['I', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'You write a message tonight .', 'あなたは 今夜 メッセージを 書きます。', ARRAY['You', 'write', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'She goes to school after school .', 'かのじょは 放課後 学校へ 行きます。', ARRAY['She', 'goes', 'to', 'school', 'after', 'school'], '.', 'go'),
('junior', 'He takes a bus tonight .', 'かれは 今夜 バスに 乗ります。', ARRAY['He', 'takes', 'a', 'bus', 'tonight'], '.', 'take'),
('junior', 'You write a message tonight .', 'あなたは 今夜 メッセージを 書きます。', ARRAY['You', 'write', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'They play soccer later .', 'かれらは あとで サッカーを します。', ARRAY['They', 'play', 'soccer', 'later'], '.', 'play'),
('junior', 'They drink water later .', 'かれらは あとで 水を 飲みます。', ARRAY['They', 'drink', 'water', 'later'], '.', 'drink'),
('junior', 'He meets my friend tonight .', 'かれは 今夜 わたしの 友だちに 会います。', ARRAY['He', 'meets', 'my', 'friend', 'tonight'], '.', 'meet'),
('junior', 'I open the door tonight .', 'わたしは 今夜 ドアを 開けます。', ARRAY['I', 'open', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'She watches TV after school .', 'かのじょは 放課後 テレビを 見ます。', ARRAY['She', 'watches', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'He writes a message now .', 'かれは 今 メッセージを 書きます。', ARRAY['He', 'writes', 'a', 'message', 'now'], '.', 'write'),
('junior', 'You run in the park every day .', 'あなたは 毎日 公園で 走ります。', ARRAY['You', 'run', 'in', 'the', 'park', 'every', 'day'], '.', 'run'),
('junior', 'We call my mother this morning .', 'わたしたちは 今朝 わたしの 母に 電話を します。', ARRAY['We', 'call', 'my', 'mother', 'this', 'morning'], '.', 'call'),
('junior', 'She eats lunch this morning .', 'かのじょは 今朝 昼ごはんを 食べます。', ARRAY['She', 'eats', 'lunch', 'this', 'morning'], '.', 'eat'),
('junior', 'They play soccer today .', 'かれらは 今日 サッカーを します。', ARRAY['They', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'You play soccer this morning .', 'あなたは 今朝 サッカーを します。', ARRAY['You', 'play', 'soccer', 'this', 'morning'], '.', 'play'),
('junior', 'They open the door later .', 'かれらは あとで ドアを 開けます。', ARRAY['They', 'open', 'the', 'door', 'later'], '.', 'open'),
('junior', 'He opens the door tonight .', 'かれは 今夜 ドアを 開けます。', ARRAY['He', 'opens', 'the', 'door', 'tonight'], '.', 'open'),
('junior', 'She plays soccer tonight .', 'かのじょは 今夜 サッカーを します。', ARRAY['She', 'plays', 'soccer', 'tonight'], '.', 'play'),
('junior', 'He drinks water now .', 'かれは 今 水を 飲みます。', ARRAY['He', 'drinks', 'water', 'now'], '.', 'drink'),
('junior', 'You listen to music later .', 'あなたは あとで 音楽を 聞きます。', ARRAY['You', 'listen', 'to', 'music', 'later'], '.', 'listen'),
('junior', 'I take a bus after school .', 'わたしは 放課後 バスに 乗ります。', ARRAY['I', 'take', 'a', 'bus', 'after', 'school'], '.', 'take'),
('junior', 'He listens to music tonight .', 'かれは 今夜 音楽を 聞きます。', ARRAY['He', 'listens', 'to', 'music', 'tonight'], '.', 'listen'),
('junior', 'They eat lunch today .', 'かれらは 今日 昼ごはんを 食べます。', ARRAY['They', 'eat', 'lunch', 'today'], '.', 'eat'),
('junior', 'He does my homework now .', 'かれは 今 わたしの 宿題を します。', ARRAY['He', 'does', 'my', 'homework', 'now'], '.', 'do'),
('junior', 'He buys some food every day .', 'かれは 毎日 食べ物を 買います。', ARRAY['He', 'buys', 'some', 'food', 'every', 'day'], '.', 'buy'),
('junior', 'I do my homework every day .', 'わたしは 毎日 わたしの 宿題を します。', ARRAY['I', 'do', 'my', 'homework', 'every', 'day'], '.', 'do'),
('junior', 'They play soccer this morning .', 'かれらは 今朝 サッカーを します。', ARRAY['They', 'play', 'soccer', 'this', 'morning'], '.', 'play'),
('junior', 'I drink water now .', 'わたしは 今 水を 飲みます。', ARRAY['I', 'drink', 'water', 'now'], '.', 'drink'),
('junior', 'You open the door now .', 'あなたは 今 ドアを 開けます。', ARRAY['You', 'open', 'the', 'door', 'now'], '.', 'open'),
('junior', 'They play soccer after school .', 'かれらは 放課後 サッカーを します。', ARRAY['They', 'play', 'soccer', 'after', 'school'], '.', 'play'),
('junior', 'We read a book now .', 'わたしたちは 今 本を 読みます。', ARRAY['We', 'read', 'a', 'book', 'now'], '.', 'read'),
('junior', 'I play soccer tonight .', 'わたしは 今夜 サッカーを します。', ARRAY['I', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'You take a bus later .', 'あなたは あとで バスに 乗ります。', ARRAY['You', 'take', 'a', 'bus', 'later'], '.', 'take'),
('junior', 'I buy some food tonight .', 'わたしは 今夜 食べ物を 買います。', ARRAY['I', 'buy', 'some', 'food', 'tonight'], '.', 'buy'),
('junior', 'He helps my friend this morning .', 'かれは 今朝 わたしの 友だちを 手伝います。', ARRAY['He', 'helps', 'my', 'friend', 'this', 'morning'], '.', 'help'),
('junior', 'They clean my room today .', 'かれらは 今日 わたしの 部屋を そうじします。', ARRAY['They', 'clean', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'They take a bus today .', 'かれらは 今日 バスに 乗ります。', ARRAY['They', 'take', 'a', 'bus', 'today'], '.', 'take'),
('junior', 'You open the door now .', 'あなたは 今 ドアを 開けます。', ARRAY['You', 'open', 'the', 'door', 'now'], '.', 'open'),
('junior', 'He opens the door now .', 'かれは 今 ドアを 開けます。', ARRAY['He', 'opens', 'the', 'door', 'now'], '.', 'open'),
('junior', 'She watches TV after school .', 'かのじょは 放課後 テレビを 見ます。', ARRAY['She', 'watches', 'TV', 'after', 'school'], '.', 'watch'),
('junior', 'You help my friend every day .', 'あなたは 毎日 わたしの 友だちを 手伝います。', ARRAY['You', 'help', 'my', 'friend', 'every', 'day'], '.', 'help'),
('junior', 'She writes a message tonight .', 'かのじょは 今夜 メッセージを 書きます。', ARRAY['She', 'writes', 'a', 'message', 'tonight'], '.', 'write'),
('junior', 'He cleans my room today .', 'かれは 今日 わたしの 部屋を そうじします。', ARRAY['He', 'cleans', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'He takes a bus every day .', 'かれは 毎日 バスに 乗ります。', ARRAY['He', 'takes', 'a', 'bus', 'every', 'day'], '.', 'take'),
('junior', 'They open the door after school .', 'かれらは 放課後 ドアを 開けます。', ARRAY['They', 'open', 'the', 'door', 'after', 'school'], '.', 'open'),
('junior', 'They listen to music every day .', 'かれらは 毎日 音楽を 聞きます。', ARRAY['They', 'listen', 'to', 'music', 'every', 'day'], '.', 'listen'),
('junior', 'I drink water every day .', 'わたしは 毎日 水を 飲みます。', ARRAY['I', 'drink', 'water', 'every', 'day'], '.', 'drink'),
('junior', 'We do my homework tonight .', 'わたしたちは 今夜 わたしの 宿題を します。', ARRAY['We', 'do', 'my', 'homework', 'tonight'], '.', 'do'),
('junior', 'We call my mother later .', 'わたしたちは あとで わたしの 母に 電話を します。', ARRAY['We', 'call', 'my', 'mother', 'later'], '.', 'call'),
('junior', 'I clean my room today .', 'わたしは 今日 わたしの 部屋を そうじします。', ARRAY['I', 'clean', 'my', 'room', 'today'], '.', 'clean'),
('junior', 'She writes a message today .', 'かのじょは 今日 メッセージを 書きます。', ARRAY['She', 'writes', 'a', 'message', 'today'], '.', 'write'),
('junior', 'I play soccer tonight .', 'わたしは 今夜 サッカーを します。', ARRAY['I', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'They go to school now .', 'かれらは 今 学校へ 行きます。', ARRAY['They', 'go', 'to', 'school', 'now'], '.', 'go'),
('junior', 'He watches TV tonight .', 'かれは 今夜 テレビを 見ます。', ARRAY['He', 'watches', 'TV', 'tonight'], '.', 'watch'),
('junior', 'We clean my room after school .', 'わたしたちは 放課後 わたしの 部屋を そうじします。', ARRAY['We', 'clean', 'my', 'room', 'after', 'school'], '.', 'clean'),
('junior', 'We study English every day .', 'わたしたちは 毎日 英語を 勉強します。', ARRAY['We', 'study', 'English', 'every', 'day'], '.', 'study'),
('junior', 'You read a book every day .', 'あなたは 毎日 本を 読みます。', ARRAY['You', 'read', 'a', 'book', 'every', 'day'], '.', 'read'),
('junior', 'We help my friend later .', 'わたしたちは あとで わたしの 友だちを 手伝います。', ARRAY['We', 'help', 'my', 'friend', 'later'], '.', 'help'),
('junior', 'They play soccer tonight .', 'かれらは 今夜 サッカーを します。', ARRAY['They', 'play', 'soccer', 'tonight'], '.', 'play'),
('junior', 'I play soccer today .', 'わたしは 今日 サッカーを します。', ARRAY['I', 'play', 'soccer', 'today'], '.', 'play'),
('junior', 'We walk to school later .', 'わたしたちは あとで 学校へ 歩いて 行きます。', ARRAY['We', 'walk', 'to', 'school', 'later'], '.', 'walk'),
('junior', 'He is meeting my friend now .', 'かれは 今 わたしの 友だちに 会っています。', ARRAY['He', 'is', 'meeting', 'my', 'friend', 'now'], '.', '進行形'),
('junior', 'Do they do my homework after school ?', '放課後 わたしの 宿題を しますか。', ARRAY['Do', 'they', 'do', 'my', 'homework', 'after', 'school'], '?', '疑問文'),
('junior', 'We are running in the park now .', 'わたしたちは 今 公園で 走っています。', ARRAY['We', 'are', 'running', 'in', 'the', 'park', 'now'], '.', '進行形'),
('junior', 'I am studying English now .', 'わたしは 今 英語を 勉強しています。', ARRAY['I', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'We called my mother yesterday .', 'わたしたちは きのう わたしの 母に 電話を しました。', ARRAY['We', 'called', 'my', 'mother', 'yesterday'], '.', '現在形'),
('junior', 'You can play soccer after school .', 'あなたは 放課後 サッカーを することが できます。', ARRAY['You', 'can', 'play', 'soccer', 'after', 'school'], '.', 'can'),
('junior', 'Does she do my homework now ?', '今 わたしの 宿題を しますか。', ARRAY['Does', 'she', 'do', 'my', 'homework', 'now'], '?', '疑問文'),
('junior', 'He cleaned my room yesterday .', 'かれは きのう わたしの 部屋を そうじしました。', ARRAY['He', 'cleaned', 'my', 'room', 'yesterday'], '.', '過去形'),
('junior', 'They are studying English now .', 'かれらは 今 英語を 勉強しています。', ARRAY['They', 'are', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'You are running in the park now .', 'あなたは 今 公園で 走っています。', ARRAY['You', 'are', 'running', 'in', 'the', 'park', 'now'], '.', '進行形'),
('junior', 'You will call my mother tonight .', 'あなたは 今夜 わたしの 母に 電話を する つもりです。', ARRAY['You', 'will', 'call', 'my', 'mother', 'tonight'], '.', 'will'),
('junior', 'He can do my homework this morning .', 'かれは 今朝 わたしの 宿題を することが できます。', ARRAY['He', 'can', 'do', 'my', 'homework', 'this', 'morning'], '.', 'can'),
('junior', 'You can call my mother now .', 'あなたは 今 わたしの 母に 電話を することが できます。', ARRAY['You', 'can', 'call', 'my', 'mother', 'now'], '.', 'can'),
('junior', 'Do you drink water today ?', '今日 水を 飲みますか。', ARRAY['Do', 'you', 'drink', 'water', 'today'], '?', '疑問文'),
('junior', 'We played soccer yesterday .', 'わたしたちは きのう サッカーを しました。', ARRAY['We', 'played', 'soccer', 'yesterday'], '.', '過去形'),
('junior', 'Does he buy some food today ?', '今日 食べ物を 買いますか。', ARRAY['Does', 'he', 'buy', 'some', 'food', 'today'], '?', '疑問文'),
('junior', 'She went to school yesterday .', 'かのじょは きのう 学校へ 行きました。', ARRAY['She', 'went', 'to', 'school', 'yesterday'], '.', '過去形'),
('junior', 'We will watch TV tonight .', 'わたしたちは 今夜 テレビを 見る つもりです。', ARRAY['We', 'will', 'watch', 'TV', 'tonight'], '.', 'will'),
('junior', 'They call my mother after school .', 'かれらは 放課後 わたしの 母に 電話を します。', ARRAY['They', 'call', 'my', 'mother', 'after', 'school'], '.', '現在形'),
('junior', 'Did you watch TV yesterday ?', 'きのう テレビを 見ましたか。', ARRAY['Did', 'you', 'watch', 'TV', 'yesterday'], '?', '疑問文'),
('junior', 'He can use my phone every day .', 'かれは 毎日 わたしの 電話を 使うことが できます。', ARRAY['He', 'can', 'use', 'my', 'phone', 'every', 'day'], '.', 'can'),
('junior', 'She will open the door tonight .', 'かのじょは 今夜 ドアを 開ける つもりです。', ARRAY['She', 'will', 'open', 'the', 'door', 'tonight'], '.', 'will'),
('junior', 'They play soccer today .', 'かれらは 今日 サッカーを します。', ARRAY['They', 'play', 'soccer', 'today'], '.', '現在形'),
('junior', 'You listened to music yesterday .', 'あなたは きのう 音楽を 聞きました。', ARRAY['You', 'listened', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'You will eat lunch after school .', 'あなたは 放課後 昼ごはんを 食べる つもりです。', ARRAY['You', 'will', 'eat', 'lunch', 'after', 'school'], '.', 'will'),
('junior', 'I watched TV yesterday .', 'わたしは きのう テレビを 見ました。', ARRAY['I', 'watched', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'You listened to music yesterday .', 'あなたは きのう 音楽を 聞きました。', ARRAY['You', 'listened', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'I am going to school now .', 'わたしは 今 学校へ 行っています。', ARRAY['I', 'am', 'going', 'to', 'school', 'now'], '.', '進行形'),
('junior', 'Does she call my mother this morning ?', '今朝 わたしの 母に 電話を しますか。', ARRAY['Does', 'she', 'call', 'my', 'mother', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do you eat lunch this morning ?', '今朝 昼ごはんを 食べますか。', ARRAY['Do', 'you', 'eat', 'lunch', 'this', 'morning'], '?', '疑問文'),
('junior', 'He is cleaning my room now .', 'かれは 今 わたしの 部屋を そうじしています。', ARRAY['He', 'is', 'cleaning', 'my', 'room', 'now'], '.', '進行形'),
('junior', 'I write a message tonight .', 'わたしは 今夜 メッセージを 書きます。', ARRAY['I', 'write', 'a', 'message', 'tonight'], '.', '現在形'),
('junior', 'He will do my homework every day .', 'かれは 毎日 わたしの 宿題を する つもりです。', ARRAY['He', 'will', 'do', 'my', 'homework', 'every', 'day'], '.', 'will'),
('junior', 'You clean my room later .', 'あなたは あとで わたしの 部屋を そうじします。', ARRAY['You', 'clean', 'my', 'room', 'later'], '.', '現在形'),
('junior', 'I can take a bus this morning .', 'わたしは 今朝 バスに 乗ることが できます。', ARRAY['I', 'can', 'take', 'a', 'bus', 'this', 'morning'], '.', 'can'),
('junior', 'You drink water later .', 'あなたは あとで 水を 飲みます。', ARRAY['You', 'drink', 'water', 'later'], '.', '現在形'),
('junior', 'Does she buy some food later ?', 'あとで 食べ物を 買いますか。', ARRAY['Does', 'she', 'buy', 'some', 'food', 'later'], '?', '疑問文'),
('junior', 'Does she use my phone this morning ?', '今朝 わたしの 電話を 使いますか。', ARRAY['Does', 'she', 'use', 'my', 'phone', 'this', 'morning'], '?', '疑問文'),
('junior', 'I will buy some food this morning .', 'わたしは 今朝 食べ物を 買う つもりです。', ARRAY['I', 'will', 'buy', 'some', 'food', 'this', 'morning'], '.', 'will'),
('junior', 'They can take a bus today .', 'かれらは 今日 バスに 乗ることが できます。', ARRAY['They', 'can', 'take', 'a', 'bus', 'today'], '.', 'can'),
('junior', 'You read a book yesterday .', 'あなたは きのう 本を 読みました。', ARRAY['You', 'read', 'a', 'book', 'yesterday'], '.', '過去形'),
('junior', 'You will help my friend every day .', 'あなたは 毎日 わたしの 友だちを 手伝う つもりです。', ARRAY['You', 'will', 'help', 'my', 'friend', 'every', 'day'], '.', 'will'),
('junior', 'You eat lunch after school .', 'あなたは 放課後 昼ごはんを 食べます。', ARRAY['You', 'eat', 'lunch', 'after', 'school'], '.', '現在形'),
('junior', 'Did she go to school yesterday ?', 'きのう 学校へ 行きましたか。', ARRAY['Did', 'she', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'We can take a bus today .', 'わたしたちは 今日 バスに 乗ることが できます。', ARRAY['We', 'can', 'take', 'a', 'bus', 'today'], '.', 'can'),
('junior', 'She can drink water today .', 'かのじょは 今日 水を 飲むことが できます。', ARRAY['She', 'can', 'drink', 'water', 'today'], '.', 'can'),
('junior', 'Do I use my phone this morning ?', 'わたしは 今朝 わたしの 電話を 使いますか。', ARRAY['Do', 'I', 'use', 'my', 'phone', 'this', 'morning'], '?', '疑問文'),
('junior', 'We will listen to music later .', 'わたしたちは あとで 音楽を 聞く つもりです。', ARRAY['We', 'will', 'listen', 'to', 'music', 'later'], '.', 'will'),
('junior', 'I am cleaning my room now .', 'わたしは 今 わたしの 部屋を そうじしています。', ARRAY['I', 'am', 'cleaning', 'my', 'room', 'now'], '.', '進行形'),
('junior', 'Do you read a book after school ?', '放課後 本を 読みますか。', ARRAY['Do', 'you', 'read', 'a', 'book', 'after', 'school'], '?', '疑問文'),
('junior', 'He can listen to music later .', 'かれは あとで 音楽を 聞くことが できます。', ARRAY['He', 'can', 'listen', 'to', 'music', 'later'], '.', 'can'),
('junior', 'I opened the door yesterday .', 'わたしは きのう ドアを 開けました。', ARRAY['I', 'opened', 'the', 'door', 'yesterday'], '.', '過去形'),
('junior', 'He can drink water after school .', 'かれは 放課後 水を 飲むことが できます。', ARRAY['He', 'can', 'drink', 'water', 'after', 'school'], '.', 'can'),
('junior', 'Does he write a message every day ?', '毎日 メッセージを 書きますか。', ARRAY['Does', 'he', 'write', 'a', 'message', 'every', 'day'], '?', '疑問文'),
('junior', 'I will do my homework today .', 'わたしは 今日 わたしの 宿題を する つもりです。', ARRAY['I', 'will', 'do', 'my', 'homework', 'today'], '.', 'will'),
('junior', 'They do my homework every day .', 'かれらは 毎日 わたしの 宿題を します。', ARRAY['They', 'do', 'my', 'homework', 'every', 'day'], '.', '現在形'),
('junior', 'We ate lunch yesterday .', 'わたしたちは きのう 昼ごはんを 食べました。', ARRAY['We', 'ate', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'We are going to school now .', 'わたしたちは 今 学校へ 行っています。', ARRAY['We', 'are', 'going', 'to', 'school', 'now'], '.', '進行形'),
('junior', 'Do they meet my friend tonight ?', '今夜 わたしの 友だちに 会いますか。', ARRAY['Do', 'they', 'meet', 'my', 'friend', 'tonight'], '?', '疑問文'),
('junior', 'Do they buy some food now ?', '今 食べ物を 買いますか。', ARRAY['Do', 'they', 'buy', 'some', 'food', 'now'], '?', '疑問文'),
('junior', 'He watches TV every day .', 'かれは 毎日 テレビを 見ます。', ARRAY['He', 'watches', 'TV', 'every', 'day'], '.', '現在形'),
('junior', 'They will listen to music every day .', 'かれらは 毎日 音楽を 聞く つもりです。', ARRAY['They', 'will', 'listen', 'to', 'music', 'every', 'day'], '.', 'will'),
('junior', 'They play soccer this morning .', 'かれらは 今朝 サッカーを します。', ARRAY['They', 'play', 'soccer', 'this', 'morning'], '.', '現在形'),
('junior', 'We clean my room later .', 'わたしたちは あとで わたしの 部屋を そうじします。', ARRAY['We', 'clean', 'my', 'room', 'later'], '.', '現在形'),
('junior', 'Do you call my mother this morning ?', '今朝 わたしの 母に 電話を しますか。', ARRAY['Do', 'you', 'call', 'my', 'mother', 'this', 'morning'], '?', '疑問文'),
('junior', 'Does he help my friend today ?', '今日 わたしの 友だちを 手伝いますか。', ARRAY['Does', 'he', 'help', 'my', 'friend', 'today'], '?', '疑問文'),
('junior', 'You do my homework now .', 'あなたは 今 わたしの 宿題を します。', ARRAY['You', 'do', 'my', 'homework', 'now'], '.', '現在形'),
('junior', 'He watched TV yesterday .', 'かれは きのう テレビを 見ました。', ARRAY['He', 'watched', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'I wrote a message yesterday .', 'わたしは きのう メッセージを 書きました。', ARRAY['I', 'wrote', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'We will write a message after school .', 'わたしたちは 放課後 メッセージを 書く つもりです。', ARRAY['We', 'will', 'write', 'a', 'message', 'after', 'school'], '.', 'will'),
('junior', 'Do you play soccer every day ?', '毎日 サッカーを しますか。', ARRAY['Do', 'you', 'play', 'soccer', 'every', 'day'], '?', '疑問文'),
('junior', 'I can clean my room this morning .', 'わたしは 今朝 わたしの 部屋を そうじすることが できます。', ARRAY['I', 'can', 'clean', 'my', 'room', 'this', 'morning'], '.', 'can'),
('junior', 'I am studying English now .', 'わたしは 今 英語を 勉強しています。', ARRAY['I', 'am', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'He wrote a message yesterday .', 'かれは きのう メッセージを 書きました。', ARRAY['He', 'wrote', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'She opened the door yesterday .', 'かのじょは きのう ドアを 開けました。', ARRAY['She', 'opened', 'the', 'door', 'yesterday'], '.', '過去形'),
('junior', 'He will watch TV this morning .', 'かれは 今朝 テレビを 見る つもりです。', ARRAY['He', 'will', 'watch', 'TV', 'this', 'morning'], '.', 'will'),
('junior', 'You are studying English now .', 'あなたは 今 英語を 勉強しています。', ARRAY['You', 'are', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'You wrote a message yesterday .', 'あなたは きのう メッセージを 書きました。', ARRAY['You', 'wrote', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'I will write a message today .', 'わたしは 今日 メッセージを 書く つもりです。', ARRAY['I', 'will', 'write', 'a', 'message', 'today'], '.', 'will'),
('junior', 'We help my friend today .', 'わたしたちは 今日 わたしの 友だちを 手伝います。', ARRAY['We', 'help', 'my', 'friend', 'today'], '.', '現在形'),
('junior', 'They are reading a book now .', 'かれらは 今 本を 読んでいます。', ARRAY['They', 'are', 'reading', 'a', 'book', 'now'], '.', '進行形'),
('junior', 'He met my friend yesterday .', 'かれは きのう わたしの 友だちに 会いました。', ARRAY['He', 'met', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'I am cleaning my room now .', 'わたしは 今 わたしの 部屋を そうじしています。', ARRAY['I', 'am', 'cleaning', 'my', 'room', 'now'], '.', '進行形'),
('junior', 'They drank water yesterday .', 'かれらは きのう 水を 飲みました。', ARRAY['They', 'drank', 'water', 'yesterday'], '.', '過去形'),
('junior', 'I am buying some food now .', 'わたしは 今 食べ物を 買っています。', ARRAY['I', 'am', 'buying', 'some', 'food', 'now'], '.', '進行形'),
('junior', 'Do you walk to school now ?', '今 学校へ 歩いて 行きますか。', ARRAY['Do', 'you', 'walk', 'to', 'school', 'now'], '?', '疑問文'),
('junior', 'You can study English tonight .', 'あなたは 今夜 英語を 勉強することが できます。', ARRAY['You', 'can', 'study', 'English', 'tonight'], '.', 'can'),
('junior', 'He met my friend yesterday .', 'かれは きのう わたしの 友だちに 会いました。', ARRAY['He', 'met', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'She is buying some food now .', 'かのじょは 今 食べ物を 買っています。', ARRAY['She', 'is', 'buying', 'some', 'food', 'now'], '.', '進行形'),
('junior', 'Do you meet my friend after school ?', '放課後 わたしの 友だちに 会いますか。', ARRAY['Do', 'you', 'meet', 'my', 'friend', 'after', 'school'], '?', '疑問文'),
('junior', 'Do they buy some food after school ?', '放課後 食べ物を 買いますか。', ARRAY['Do', 'they', 'buy', 'some', 'food', 'after', 'school'], '?', '疑問文'),
('junior', 'You will buy some food tomorrow .', 'あなたは 明日 食べ物を 買う つもりです。', ARRAY['You', 'will', 'buy', 'some', 'food', 'tomorrow'], '.', 'will'),
('junior', 'She is reading a book now .', 'かのじょは 今 本を 読んでいます。', ARRAY['She', 'is', 'reading', 'a', 'book', 'now'], '.', '進行形'),
('junior', 'They will listen to music tomorrow .', 'かれらは 明日 音楽を 聞く つもりです。', ARRAY['They', 'will', 'listen', 'to', 'music', 'tomorrow'], '.', 'will'),
('junior', 'You are drinking water now .', 'あなたは 今 水を 飲んでいます。', ARRAY['You', 'are', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'They drank water yesterday .', 'かれらは きのう 水を 飲みました。', ARRAY['They', 'drank', 'water', 'yesterday'], '.', '過去形'),
('junior', 'You read a book yesterday .', 'あなたは きのう 本を 読みました。', ARRAY['You', 'read', 'a', 'book', 'yesterday'], '.', '過去形'),
('junior', 'Do they watch TV every day ?', '毎日 テレビを 見ますか。', ARRAY['Do', 'they', 'watch', 'TV', 'every', 'day'], '?', '疑問文'),
('junior', 'Did I go to school yesterday ?', 'わたしは きのう 学校へ 行きましたか。', ARRAY['Did', 'I', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'She is writing a message now .', 'かのじょは 今 メッセージを 書いています。', ARRAY['She', 'is', 'writing', 'a', 'message', 'now'], '.', '進行形'),
('junior', 'He will help my friend tomorrow .', 'かれは 明日 わたしの 友だちを 手伝う つもりです。', ARRAY['He', 'will', 'help', 'my', 'friend', 'tomorrow'], '.', 'will'),
('junior', 'I will read a book this morning .', 'わたしは 今朝 本を 読む つもりです。', ARRAY['I', 'will', 'read', 'a', 'book', 'this', 'morning'], '.', 'will'),
('junior', 'I studied English yesterday .', 'わたしは きのう 英語を 勉強しました。', ARRAY['I', 'studied', 'English', 'yesterday'], '.', '過去形'),
('junior', 'She plays soccer now .', 'かのじょは 今 サッカーを します。', ARRAY['She', 'plays', 'soccer', 'now'], '.', '現在形'),
('junior', 'Do we watch TV now ?', '今 テレビを 見ますか。', ARRAY['Do', 'we', 'watch', 'TV', 'now'], '?', '疑問文'),
('junior', 'We can use my phone every day .', 'わたしたちは 毎日 わたしの 電話を 使うことが できます。', ARRAY['We', 'can', 'use', 'my', 'phone', 'every', 'day'], '.', 'can'),
('junior', 'He is running in the park now .', 'かれは 今 公園で 走っています。', ARRAY['He', 'is', 'running', 'in', 'the', 'park', 'now'], '.', '進行形'),
('junior', 'I went to school yesterday .', 'わたしは きのう 学校へ 行きました。', ARRAY['I', 'went', 'to', 'school', 'yesterday'], '.', '過去形'),
('junior', 'We met my friend yesterday .', 'わたしたちは きのう わたしの 友だちに 会いました。', ARRAY['We', 'met', 'my', 'friend', 'yesterday'], '.', '過去形'),
('junior', 'I will meet my friend tonight .', 'わたしは 今夜 わたしの 友だちに 会う つもりです。', ARRAY['I', 'will', 'meet', 'my', 'friend', 'tonight'], '.', 'will'),
('junior', 'We can write a message after school .', 'わたしたちは 放課後 メッセージを 書くことが できます。', ARRAY['We', 'can', 'write', 'a', 'message', 'after', 'school'], '.', 'can'),
('junior', 'We ran in the park yesterday .', 'わたしたちは きのう 公園で 走りました。', ARRAY['We', 'ran', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'I am listening to music now .', 'わたしは 今 音楽を 聞いています。', ARRAY['I', 'am', 'listening', 'to', 'music', 'now'], '.', '進行形'),
('junior', 'You can help my friend every day .', 'あなたは 毎日 わたしの 友だちを 手伝うことが できます。', ARRAY['You', 'can', 'help', 'my', 'friend', 'every', 'day'], '.', 'can'),
('junior', 'He ran in the park yesterday .', 'かれは きのう 公園で 走りました。', ARRAY['He', 'ran', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'I will clean my room this morning .', 'わたしは 今朝 わたしの 部屋を そうじする つもりです。', ARRAY['I', 'will', 'clean', 'my', 'room', 'this', 'morning'], '.', 'will'),
('junior', 'They can drink water today .', 'かれらは 今日 水を 飲むことが できます。', ARRAY['They', 'can', 'drink', 'water', 'today'], '.', 'can'),
('junior', 'We will write a message now .', 'わたしたちは 今 メッセージを 書く つもりです。', ARRAY['We', 'will', 'write', 'a', 'message', 'now'], '.', 'will'),
('junior', 'We can read a book this morning .', 'わたしたちは 今朝 本を 読むことが できます。', ARRAY['We', 'can', 'read', 'a', 'book', 'this', 'morning'], '.', 'can'),
('junior', 'She uses my phone later .', 'かのじょは あとで わたしの 電話を 使います。', ARRAY['She', 'uses', 'my', 'phone', 'later'], '.', '現在形'),
('junior', 'She will drink water tonight .', 'かのじょは 今夜 水を 飲む つもりです。', ARRAY['She', 'will', 'drink', 'water', 'tonight'], '.', 'will'),
('junior', 'He goes to school today .', 'かれは 今日 学校へ 行きます。', ARRAY['He', 'goes', 'to', 'school', 'today'], '.', '現在形'),
('junior', 'They will meet my friend this morning .', 'かれらは 今朝 わたしの 友だちに 会う つもりです。', ARRAY['They', 'will', 'meet', 'my', 'friend', 'this', 'morning'], '.', 'will'),
('junior', 'We can read a book this morning .', 'わたしたちは 今朝 本を 読むことが できます。', ARRAY['We', 'can', 'read', 'a', 'book', 'this', 'morning'], '.', 'can'),
('junior', 'They cleaned my room yesterday .', 'かれらは きのう わたしの 部屋を そうじしました。', ARRAY['They', 'cleaned', 'my', 'room', 'yesterday'], '.', '過去形'),
('junior', 'I took a bus yesterday .', 'わたしは きのう バスに 乗りました。', ARRAY['I', 'took', 'a', 'bus', 'yesterday'], '.', '過去形'),
('junior', 'He listens to music every day .', 'かれは 毎日 音楽を 聞きます。', ARRAY['He', 'listens', 'to', 'music', 'every', 'day'], '.', '現在形'),
('junior', 'She eats lunch now .', 'かのじょは 今 昼ごはんを 食べます。', ARRAY['She', 'eats', 'lunch', 'now'], '.', '現在形'),
('junior', 'They write a message this morning .', 'かれらは 今朝 メッセージを 書きます。', ARRAY['They', 'write', 'a', 'message', 'this', 'morning'], '.', '現在形'),
('junior', 'I can clean my room today .', 'わたしは 今日 わたしの 部屋を そうじすることが できます。', ARRAY['I', 'can', 'clean', 'my', 'room', 'today'], '.', 'can'),
('junior', 'We can do my homework now .', 'わたしたちは 今 わたしの 宿題を することが できます。', ARRAY['We', 'can', 'do', 'my', 'homework', 'now'], '.', 'can'),
('junior', 'Do I study English this morning ?', 'わたしは 今朝 英語を 勉強しますか。', ARRAY['Do', 'I', 'study', 'English', 'this', 'morning'], '?', '疑問文'),
('junior', 'You can run in the park tonight .', 'あなたは 今夜 公園で 走ることが できます。', ARRAY['You', 'can', 'run', 'in', 'the', 'park', 'tonight'], '.', 'can'),
('junior', 'She will meet my friend today .', 'かのじょは 今日 わたしの 友だちに 会う つもりです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'today'], '.', 'will'),
('junior', 'I am playing soccer now .', 'わたしは 今 サッカーを しています。', ARRAY['I', 'am', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'You are helping my friend now .', 'あなたは 今 わたしの 友だちを 手伝っています。', ARRAY['You', 'are', 'helping', 'my', 'friend', 'now'], '.', '進行形'),
('junior', 'Do I watch TV today ?', 'わたしは 今日 テレビを 見ますか。', ARRAY['Do', 'I', 'watch', 'TV', 'today'], '?', '疑問文'),
('junior', 'Does he read a book this morning ?', '今朝 本を 読みますか。', ARRAY['Does', 'he', 'read', 'a', 'book', 'this', 'morning'], '?', '疑問文'),
('junior', 'You are opening the door now .', 'あなたは 今 ドアを 開けています。', ARRAY['You', 'are', 'opening', 'the', 'door', 'now'], '.', '進行形'),
('junior', 'We can listen to music this morning .', 'わたしたちは 今朝 音楽を 聞くことが できます。', ARRAY['We', 'can', 'listen', 'to', 'music', 'this', 'morning'], '.', 'can'),
('junior', 'They will do my homework tomorrow .', 'かれらは 明日 わたしの 宿題を する つもりです。', ARRAY['They', 'will', 'do', 'my', 'homework', 'tomorrow'], '.', 'will'),
('junior', 'They will take a bus today .', 'かれらは 今日 バスに 乗る つもりです。', ARRAY['They', 'will', 'take', 'a', 'bus', 'today'], '.', 'will'),
('junior', 'You will do my homework after school .', 'あなたは 放課後 わたしの 宿題を する つもりです。', ARRAY['You', 'will', 'do', 'my', 'homework', 'after', 'school'], '.', 'will'),
('junior', 'She ate lunch yesterday .', 'かのじょは きのう 昼ごはんを 食べました。', ARRAY['She', 'ate', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'He will study English later .', 'かれは あとで 英語を 勉強する つもりです。', ARRAY['He', 'will', 'study', 'English', 'later'], '.', 'will'),
('junior', 'Do they buy some food this morning ?', '今朝 食べ物を 買いますか。', ARRAY['Do', 'they', 'buy', 'some', 'food', 'this', 'morning'], '?', '疑問文'),
('junior', 'He can go to school tonight .', 'かれは 今夜 学校へ 行くことが できます。', ARRAY['He', 'can', 'go', 'to', 'school', 'tonight'], '.', 'can'),
('junior', 'I read a book now .', 'わたしは 今 本を 読みます。', ARRAY['I', 'read', 'a', 'book', 'now'], '.', '現在形'),
('junior', 'You can walk to school every day .', 'あなたは 毎日 学校へ 歩いて 行くことが できます。', ARRAY['You', 'can', 'walk', 'to', 'school', 'every', 'day'], '.', 'can'),
('junior', 'We are writing a message now .', 'わたしたちは 今 メッセージを 書いています。', ARRAY['We', 'are', 'writing', 'a', 'message', 'now'], '.', '進行形'),
('junior', 'They are helping my friend now .', 'かれらは 今 わたしの 友だちを 手伝っています。', ARRAY['They', 'are', 'helping', 'my', 'friend', 'now'], '.', '進行形'),
('junior', 'She ate lunch yesterday .', 'かのじょは きのう 昼ごはんを 食べました。', ARRAY['She', 'ate', 'lunch', 'yesterday'], '.', '過去形'),
('junior', 'We are playing soccer now .', 'わたしたちは 今 サッカーを しています。', ARRAY['We', 'are', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Does he help my friend this morning ?', '今朝 わたしの 友だちを 手伝いますか。', ARRAY['Does', 'he', 'help', 'my', 'friend', 'this', 'morning'], '?', '疑問文'),
('junior', 'Did she eat lunch yesterday ?', 'きのう 昼ごはんを 食べましたか。', ARRAY['Did', 'she', 'eat', 'lunch', 'yesterday'], '?', '疑問文'),
('junior', 'She did my homework yesterday .', 'かのじょは きのう わたしの 宿題を しました。', ARRAY['She', 'did', 'my', 'homework', 'yesterday'], '.', '過去形'),
('junior', 'Do they play soccer now ?', '今 サッカーを しますか。', ARRAY['Do', 'they', 'play', 'soccer', 'now'], '?', '疑問文'),
('junior', 'You are cleaning my room now .', 'あなたは 今 わたしの 部屋を そうじしています。', ARRAY['You', 'are', 'cleaning', 'my', 'room', 'now'], '.', '進行形'),
('junior', 'I am running in the park now .', 'わたしは 今 公園で 走っています。', ARRAY['I', 'am', 'running', 'in', 'the', 'park', 'now'], '.', '進行形'),
('junior', 'Do we do my homework this morning ?', '今朝 わたしの 宿題を しますか。', ARRAY['Do', 'we', 'do', 'my', 'homework', 'this', 'morning'], '?', '疑問文'),
('junior', 'I am meeting my friend now .', 'わたしは 今 わたしの 友だちに 会っています。', ARRAY['I', 'am', 'meeting', 'my', 'friend', 'now'], '.', '進行形'),
('junior', 'We are playing soccer now .', 'わたしたちは 今 サッカーを しています。', ARRAY['We', 'are', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Do you play soccer tonight ?', '今夜 サッカーを しますか。', ARRAY['Do', 'you', 'play', 'soccer', 'tonight'], '?', '疑問文'),
('junior', 'We meet my friend today .', 'わたしたちは 今日 わたしの 友だちに 会います。', ARRAY['We', 'meet', 'my', 'friend', 'today'], '.', '現在形'),
('junior', 'Do I listen to music later ?', 'わたしは あとで 音楽を 聞きますか。', ARRAY['Do', 'I', 'listen', 'to', 'music', 'later'], '?', '疑問文'),
('junior', 'Does she use my phone today ?', '今日 わたしの 電話を 使いますか。', ARRAY['Does', 'she', 'use', 'my', 'phone', 'today'], '?', '疑問文'),
('junior', 'You are drinking water now .', 'あなたは 今 水を 飲んでいます。', ARRAY['You', 'are', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'He can run in the park later .', 'かれは あとで 公園で 走ることが できます。', ARRAY['He', 'can', 'run', 'in', 'the', 'park', 'later'], '.', 'can'),
('junior', 'You will help my friend after school .', 'あなたは 放課後 わたしの 友だちを 手伝う つもりです。', ARRAY['You', 'will', 'help', 'my', 'friend', 'after', 'school'], '.', 'will'),
('junior', 'I will use my phone every day .', 'わたしは 毎日 わたしの 電話を 使う つもりです。', ARRAY['I', 'will', 'use', 'my', 'phone', 'every', 'day'], '.', 'will'),
('junior', 'He is listening to music now .', 'かれは 今 音楽を 聞いています。', ARRAY['He', 'is', 'listening', 'to', 'music', 'now'], '.', '進行形'),
('junior', 'I used my phone yesterday .', 'わたしは きのう わたしの 電話を 使いました。', ARRAY['I', 'used', 'my', 'phone', 'yesterday'], '.', '過去形'),
('junior', 'We listened to music yesterday .', 'わたしたちは きのう 音楽を 聞きました。', ARRAY['We', 'listened', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'Did you go to school yesterday ?', 'きのう 学校へ 行きましたか。', ARRAY['Did', 'you', 'go', 'to', 'school', 'yesterday'], '?', '疑問文'),
('junior', 'He took a bus yesterday .', 'かれは きのう バスに 乗りました。', ARRAY['He', 'took', 'a', 'bus', 'yesterday'], '.', '過去形'),
('junior', 'She will meet my friend this morning .', 'かのじょは 今朝 わたしの 友だちに 会う つもりです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'this', 'morning'], '.', 'will'),
('junior', 'She is opening the door now .', 'かのじょは 今 ドアを 開けています。', ARRAY['She', 'is', 'opening', 'the', 'door', 'now'], '.', '進行形'),
('junior', 'She will take a bus later .', 'かのじょは あとで バスに 乗る つもりです。', ARRAY['She', 'will', 'take', 'a', 'bus', 'later'], '.', 'will'),
('junior', 'Do we study English now ?', '今 英語を 勉強しますか。', ARRAY['Do', 'we', 'study', 'English', 'now'], '?', '疑問文'),
('junior', 'He listened to music yesterday .', 'かれは きのう 音楽を 聞きました。', ARRAY['He', 'listened', 'to', 'music', 'yesterday'], '.', '過去形'),
('junior', 'We are studying English now .', 'わたしたちは 今 英語を 勉強しています。', ARRAY['We', 'are', 'studying', 'English', 'now'], '.', '進行形'),
('junior', 'Do they go to school now ?', '今 学校へ 行きますか。', ARRAY['Do', 'they', 'go', 'to', 'school', 'now'], '?', '疑問文'),
('junior', 'He will write a message today .', 'かれは 今日 メッセージを 書く つもりです。', ARRAY['He', 'will', 'write', 'a', 'message', 'today'], '.', 'will'),
('junior', 'She can meet my friend every day .', 'かのじょは 毎日 わたしの 友だちに 会うことが できます。', ARRAY['She', 'can', 'meet', 'my', 'friend', 'every', 'day'], '.', 'can'),
('junior', 'You can do my homework later .', 'あなたは あとで わたしの 宿題を することが できます。', ARRAY['You', 'can', 'do', 'my', 'homework', 'later'], '.', 'can'),
('junior', 'You can watch TV today .', 'あなたは 今日 テレビを 見ることが できます。', ARRAY['You', 'can', 'watch', 'TV', 'today'], '.', 'can'),
('junior', 'You will walk to school now .', 'あなたは 今 学校へ 歩いて 行く つもりです。', ARRAY['You', 'will', 'walk', 'to', 'school', 'now'], '.', 'will'),
('junior', 'They can eat lunch this morning .', 'かれらは 今朝 昼ごはんを 食べることが できます。', ARRAY['They', 'can', 'eat', 'lunch', 'this', 'morning'], '.', 'can'),
('junior', 'You can clean my room this morning .', 'あなたは 今朝 わたしの 部屋を そうじすることが できます。', ARRAY['You', 'can', 'clean', 'my', 'room', 'this', 'morning'], '.', 'can'),
('junior', 'Do they call my mother today ?', '今日 わたしの 母に 電話を しますか。', ARRAY['Do', 'they', 'call', 'my', 'mother', 'today'], '?', '疑問文'),
('junior', 'He ran in the park yesterday .', 'かれは きのう 公園で 走りました。', ARRAY['He', 'ran', 'in', 'the', 'park', 'yesterday'], '.', '現在形'),
('junior', 'You wrote a message yesterday .', 'あなたは きのう メッセージを 書きました。', ARRAY['You', 'wrote', 'a', 'message', 'yesterday'], '.', '過去形'),
('junior', 'He ran in the park yesterday .', 'かれは きのう 公園で 走りました。', ARRAY['He', 'ran', 'in', 'the', 'park', 'yesterday'], '.', '過去形'),
('junior', 'He watched TV yesterday .', 'かれは きのう テレビを 見ました。', ARRAY['He', 'watched', 'TV', 'yesterday'], '.', '過去形'),
('junior', 'She will take a bus tonight .', 'かのじょは 今夜 バスに 乗る つもりです。', ARRAY['She', 'will', 'take', 'a', 'bus', 'tonight'], '.', 'will'),
('junior', 'You are drinking water now .', 'あなたは 今 水を 飲んでいます。', ARRAY['You', 'are', 'drinking', 'water', 'now'], '.', '進行形'),
('junior', 'She will meet my friend tomorrow .', 'かのじょは 明日 わたしの 友だちに 会う つもりです。', ARRAY['She', 'will', 'meet', 'my', 'friend', 'tomorrow'], '.', 'will'),
('junior', 'They are playing soccer now .', 'かれらは 今 サッカーを しています。', ARRAY['They', 'are', 'playing', 'soccer', 'now'], '.', '進行形'),
('junior', 'Do they listen to music this morning ?', '今朝 音楽を 聞きますか。', ARRAY['Do', 'they', 'listen', 'to', 'music', 'this', 'morning'], '?', '疑問文'),
('junior', 'Do I call my mother today ?', 'わたしは 今日 わたしの 母に 電話を しますか。', ARRAY['Do', 'I', 'call', 'my', 'mother', 'today'], '?', '疑問文');
